`ifndef GUARD_CUST_APB_MASTER_SEQUENCE_COLLECTION_SV
`define GUARD_CUST_APB_MASTER_SEQUENCE_COLLECTION_SV
/**
 * Abstract:
 * cust_apb_master_directed_sequence is used by test to provide initiator
 * scenario information to the Master agent present in the System Env.
 * This class defines a sequence in which a APB WRITE followed by a APB READ
 * sequence is generated by assigning values to the transactions rather than
 * randomization, and then transmitted using `uvm_send.
 *
 * Execution phase: main_phase
 * Sequencer: Master agent sequencer
 */

class cust_apb_master_directed_sequence extends svt_apb_master_base_sequence;

  /** Parameter that controls the number of transactions that will be generated */
  rand bit[31:0] tran_addr;
  rand bit[3:0]  tran_pstrb;
  rand bit[31:0] tran_data;
  rand bit[3:0]  tran_size;
  rand svt_apb_transaction::xact_type_enum tran_type;

  /** Constraint for seq_xact_type */
  constraint c_tran_type {
    tran_type inside {svt_apb_transaction::WRITE,svt_apb_transaction::READ};
    
  }

  /** UVM Object Utility macro */
  `uvm_object_utils(cust_apb_master_directed_sequence)

  /** Class Constructor */
  function new(string name="cust_apb_master_directed_sequence");
    super.new(name);
  endfunction
  
  virtual task body();
    svt_apb_master_transaction trans;
    `uvm_info("body", "Entered ...", UVM_HIGH)

    super.body();
    `uvm_do_with(trans, {
                          xact_type == tran_type;
                          address   == tran_addr;
						  if (xact_type == svt_apb_transaction::WRITE) {
						    pstrb     == tran_pstrb;						  
						    data      == tran_data;
					      }		
				        })
       
    `uvm_info("APB_TRANS", $sformatf("[CMD] DIR:%s ADDR[%0h] STRB:%0b", trans.xact_type.name(), trans.address,  trans.pstrb), UVM_LOW)

    get_response(rsp);
	
	if (trans.xact_type == svt_apb_transaction::READ) tran_data = trans.data;

	`uvm_info("APB_TRANS", $sformatf("[%0s] DIR:%s ADDR[%0h]:%0h STRB:%0b", (trans.xact_type == svt_apb_transaction::READ ? "DATA" : "RESP"),  trans.xact_type.name(), trans.address, trans.data,  trans.pstrb), UVM_LOW)

    `uvm_info("body", "Exiting...", UVM_HIGH)
  endtask: body

endclass: cust_apb_master_directed_sequence

/**
 * Abstract:
 * class cust_apb_master_random_discrete_sequence defines a sequence that generates a
 * random discrete master transaction.  This sequence is used by the
 * apb_master_random_discrete_virtual_sequence which is set up as the default
 * sequence for this environment.
 *
 * Execution phase: main_phase
 * Sequencer: Virtual sequencer in APB System ENV
 */


class cust_apb_master_random_discrete_sequence extends svt_apb_master_base_sequence;

   /** Parameter that controls the number of transactions that will be generated */
   rand int unsigned sequence_length = 10;

  /** UVM Object Utility macro */
  `uvm_object_utils(cust_apb_master_random_discrete_sequence)

  /** Constrain the sequence length to a reasonable value */
  constraint reasonable_sequence_length {
    sequence_length <= 100;
  }

  /** Class Constructor */
  function new (string name = "cust_apb_master_random_discrete_sequence");
     super.new(name);
  endfunction : new

  virtual task body();
    bit status;

    `uvm_info("body", "Entered ...", UVM_HIGH)

    super.body();

    status = uvm_config_db#(int unsigned)::get(null, get_full_name(), "sequence_length", sequence_length);
    `uvm_info("body", $sformatf("sequence_length is %0d as a result of %0s.", sequence_length, status ? "config DB" : "randomization"), UVM_LOW);

    for(int i = 0; i < sequence_length; i++) begin
      `uvm_do(req)
    end

    `uvm_info("body", "Exiting...", UVM_HIGH)
  endtask: body
  
endclass: cust_apb_master_random_discrete_sequence

/**
 * Abstract:
 * cust_apb_master_wr_rd_sequence is used by test to provide initiator scenario
 * information to the Master agent present in the System agent.  This class
 * defines a sequence in which a random APB WRITE followed by a random APB READ
 * sequence is generated using `uvm_do_with macros.
 *
 * Execution phase: main_phase
 * Sequencer: Master agent sequencer
 */


class cust_apb_master_wr_rd_sequence extends svt_apb_master_base_sequence;

  /** Parameter that controls the number of transactions that will be generated */
  rand int unsigned sequence_length = 10;

  /** Constrain the sequence length to a reasonable value */
  constraint reasonable_sequence_length {
    sequence_length <= 100;
  }

  /** UVM Object Utility macro */
  `uvm_object_utils(cust_apb_master_wr_rd_sequence)

  /** Class Constructor */
  function new(string name="cust_apb_master_wr_rd_sequence");
    super.new(name);
  endfunction
  
  virtual task body();
    bit status;
    bit [`SVT_APB_MAX_ADDR_WIDTH -1:0] addr;
    `uvm_info("body", "Entered ...", UVM_HIGH)

    super.body();

    status = uvm_config_db #(int unsigned)::get(null, get_full_name(), "sequence_length", sequence_length);
    `uvm_info("body", $sformatf("sequence_length is %0d as a result of %0s.", sequence_length, status ? "config DB" : "randomization"), UVM_LOW);
    
    repeat (sequence_length) begin
      `ifndef SVT_UVM_1800_2_2017_OR_HIGHER
        `uvm_do_with(req, { xact_type == svt_apb_transaction::WRITE; })
        addr = req.address;
        `uvm_do_with(req, { xact_type == svt_apb_transaction::READ; address == addr;})
      `else 
        `uvm_do(req,,, { xact_type == svt_apb_transaction::WRITE; })
        addr = req.address;
        `uvm_do(req,,, { xact_type == svt_apb_transaction::READ; address == addr;})
      `endif
    end

    `uvm_info("body", "Exiting...", UVM_HIGH)
  endtask: body

endclass: cust_apb_master_wr_rd_sequence

/**
 * Abstract:
 * class cust_apb_null_virtual_sequence defines a virtual sequence cust_apb_null_virtual_sequence.
 * cust_apb_null_virtual_sequence is a no-operation sequence since the body() method
 * has empty implementation.
 *
 * cust_apb_null_virtual_sequence is used by directed_test and random_wr_rd_test.
 * These tests load this null sequence into the virtual sequencer in testbench
 * ENV, as these tests use the sequencer in the master agent.
 *
 * Execution phase: main_phase 
 * Sequencer: Can be used with any sequencer in which default sequence needs to be
 * overridden with a null sequence. In this example, this sequence has been used with
 * virtual sequencer in the testbench environment.
 */

class cust_apb_null_virtual_sequence extends uvm_sequence;

  /** UVM Object Utility macro */
  `uvm_object_utils(cust_apb_null_virtual_sequence)

  /** Class Constructor */
  function new (string name = "cust_apb_null_virtual_sequence");
     super.new(name);
  endfunction : new

  /** Need an empty body function to override the warning from the UVM base class */
  virtual task body();
  endtask

endclass : cust_apb_null_virtual_sequence 

`endif // GUARD_CUST_APB_MASTER_SEQUENCE_COLLECTION_SV
