// GENERATED by dv_harness/uvm_generator/bind_mechanism_generator.py --
// dv_uvm_hook.svh for protocol 'usb'. Included from DUT/MODEL/<model>.v's
// Hook 1 (`` `ifdef DV_UVM ``); everything here runs at TOP-MODULE SCOPE
// because it cannot be `bind`-ed (CORE/ip-uvm-dv-gen/SKILL.md "What must be
// at top-module scope" table): the macro redirect (preprocessing is
// sequential -- placed before the model's task definitions so every
// register access inside those tasks is redirected with no edit to any of
// them), the bridge instances (patterns reach them by hierarchical path),
// and the pattern `initial` block (declares the variables patterns use,
// under the original names).

// -- macro redirect (must precede the model's task definitions) --
`define CPUWRITE1B dv_uvm_cpuwrite1b
`define CPUWRITE2B dv_uvm_cpuwrite2b
`define CPUWRITE4B dv_uvm_cpuwrite4b

// -- bridge instances + pattern initial block (top-module scope) --
  // TODO_PLACEHOLDER: bridge instance(s) connecting dv_uvm_cpuwrite*b to the real DUT register-write path go here -- not yet designed in this pass (needs the same APB/CPU-side path evidence as ss_cpu_m_* signals at DUT.RTLCAT.TOP_ALL.v:25950-25959, which this pass only located but did not yet wire).

initial run_test();
