// GENERATED by dv_harness/uvm_generator/bind_mechanism_generator.py --
// every bind target below is evidence-supplied (bind_entries), never invented.
// Convention: CORE/ip-uvm-dv-gen/SKILL.md -- bind targeted at where the signal
// is actually declared in the DUT hierarchy, not assumed at the subsystem boundary.

// phy0_sram_init_done observed directly in real production pattern D:/DV/Task/USB/patterns/USB2_con.txt:49 as the gate for device-side PHY SRAM init completion before the device controller registers (CPUWRITE 0x1271_xxxx) are safely programmed; u_usbtop is a 2-wide array per usb-tb-scaffold SKILL.md:110 so index [0] must be explicit, never assumed.
bind `SS_VOUT.u_usbtop[0] dv_uvm_probe u_usb0_sram_init_probe (.phy0_sram_init_done(phy0_sram_init_done));
