export const meta = {
  name: 'asset-processing-table-reverify',
  description: 'Re-verify with CURRENT real evidence the asset-processing table (hierarchy/phy_boundary/regmap/sys_regmap/intent/init_seq/constraints/vip_ref extraction), the 4 key judgments (PHY-decides-bind, register-file division of labor, command.txt authority, VIP-source symbol-indexing), the 9-level conflict authority order, and the 3-tier context budget -- close only genuine remaining gaps',
  phases: [
    { title: 'Audit', detail: '4 section audits against already-built code, in parallel' },
    { title: 'Close', detail: 'sequential fix pass over every confirmed real, in-scope gap' },
    { title: 'Report', detail: 'independent verification' },
  ],
}

const CORE_PRINCIPLES = `
Related infrastructure already built this session (verify current truth,
don't assume): dv_harness/env_manifest.py (hierarchy/VIP/env facts),
run_profile.json + run_profile_to_justfile.py (compile options / defines /
plusargs / UVM_TESTNAME as the agent's execution verb, derived FROM
reference command.txt, never hand-composed), dv_harness/reference_pattern_audit.py
(line-by-line reference command.txt register-write audit, host/DUT symmetry),
dv_harness/connectivity.py (bind-location 4 hard rules, T1-T4 tiers,
3 machine gates, checker/scoreboard table), dv_harness/mcp/ (5-verb
read-only query interface), dv_harness/address_map_verifier.py (register
address extraction from 3 sources). Several OTHER workflows are running
concurrently right now re-verifying overlapping pieces of this same
infrastructure from different angles (env.manifest 3-layer facts, MCP verbs,
bind-location rules, 3 machine gates, checker/scoreboard table) -- this
workflow's job is specifically the asset-processing TABLE's full artifact
list (which may include artifact types NOT yet covered by any of that:
phy_boundary.json, sys_regmap.json, intent.md, init_seq.yaml, constraints.md,
vip_ref/<protocol>.md, VIP-source symbol-indexing, pattern/<protocol>/), the
4 SPECIFIC judgments below (which are more precise/different framings than
what other workflows check), the 9-level conflict authority order (a wholly
new, specific requirement), and the 3-tier context budget (also largely new).

Verdict format per requirement, one of:
- READY: real, working, evidenced, matches the spec's specifics.
- PARTIAL: real but incomplete -- name exactly what's missing vs. the spec.
- BLOCKED: does not exist, a real closeable gap.
Cite real file:line or real command output for every verdict. Audit only --
do not modify any file in this phase.
`

phase('Audit')

const auditAssetTable = agent(`${CORE_PRINCIPLES}

## Your scope: the full asset-processing table

For EACH row below, check whether the real artifact type exists, is generated by real code (not hand-authored once and left stale), and is actually consumed downstream as described:

| Asset | Extracted to | Primarily feeds | Re-extract trigger |
|---|---|---|---|
| DUT RTL | hierarchy.json (scope tree), port/param table | bind path, VIP count | RTL commit |
| PHY model | phy_boundary.json: PHY<->controller interface type, serial/parallel boundary | bind-location decision | PHY version update |
| top testbench | existing bind list, clock/reset source, existing VIP instances | T1 settled facts | every commit |
| whole chip script | run_profile.json: compile options, defines, plusargs, UVM_TESTNAME convention | agent's execution verb | manual |
| reference command.txt | same as above, AND is the sole authority | execution method | manual |
| whole chip database | NOT extracted, only queried (ucli scope -tree, waveform API) | connectivity verification | -- |
| DUT register file | RAL model + regmap.json | scoreboard's address decode, init sequence | register file update |
| Global register file | sys_regmap.json: clock/reset/mux/pinmux control bits | mode-determining bits (see judgment 2 below) | same as above |
| DUT controller doc | intent.md: state machine, modes, legal drop/backpressure conditions | scoreboard's ordering and exemption conditions | manual |
| IP programming guide | init_seq.yaml: register write order and wait conditions | directed test, connectivity check | manual |
| IP user guide / digital+analog doc | constraints.md: timing, electrical limits, untestable items | exemption list | manual |
| VIP document | vip_ref/<protocol>.md (distilled) | config field semantics, built-in check list | VIP version update |
| VIP source | NOT loaded into context, only symbol-indexed (class/method names + file:line) | targeted read when needed | VIP version update |
| VIP example | pattern/<protocol>/: minimal executable skeleton | environment-generation template | VIP version update |

Report your verdict per the required format, ONE ROW AT A TIME (14 rows) -- which real file/module implements each row's "extracted to" artifact, whether it's real generated code or missing, and whether the "primarily feeds" consumption is real (grep for actual consumers) or aspirational.`, {label: 'audit:asset-table', phase: 'Audit'})

const auditFourJudgments = agent(`${CORE_PRINCIPLES}

## Your scope: the 4 key judgments

### Judgment 1: PHY model decides bind location, not RTL naming
The same USB IP's VIP can mount at UTMI/PIPE (parallel, aligned to the controller boundary) or at the serial side (needs PHY model cooperation). Same for CSI-2: D-PHY lane layer vs PPI layer. Rule: the PHY model's EXISTENCE AND TYPE decides the mount layer FIRST, then the hierarchy path is found -- doing it backwards (find path first, then decide layer) is exactly a T3 guess. This must be a HARD RULE written into CLAUDE.md.
Check: does CLAUDE.md's Bind-Location Rules section (or anywhere else) state this specific PHY-model-decides-layer-before-path ordering rule? It's a different, more specific rule than the 4 already-documented bind-location rules (bare-module-name/centralized-bind-file/explicit-clock-reset/no-generate-loop) -- confirm honestly whether this specific judgment is present or missing.

### Judgment 2: the two register files' division of labor
The Global register file is often overlooked but most likely to break connectivity checks: clock enable, reset release, pinmux, PHY select bits -- if these aren't written first, the interface NEVER toggles, and the agent will misdiagnose it as "wrong bind path." So Gate 2 (static connectivity)'s PRECONDITION is: apply the Global register file's enable sequence FIRST. This sequence should be extracted from the programming guide into init_seq.yaml, becoming the fixed prologue of the connectivity check.
Check: does connectivity.py's Gate 2 (static connectivity) actually require/apply a Global-register-file enable sequence as a precondition before checking for toggle/deassert/non-X, or does it just check raw signal activity with no register-init precondition (which would make a real "registers never written" case look identical to a real "wrong bind path" case -- exactly the confusion this judgment warns about)?

### Judgment 3: reference command.txt is the highest authority
Docs go stale, scripts branch, but command.txt is the actually-runnable one. Required: (a) agent must never compose a vcs command line itself, only invoke a just recipe derived FROM command.txt; (b) if the agent believes a new option is needed, it goes through the question queue, the agent never adds it itself; (c) this is also L5's reproducibility baseline.
Check: does run_profile_to_justfile.py's real pipeline enforce (a) -- is there any real code path where an agent (or the generator) still composes a raw vcs/simv command line directly instead of going through a derived just recipe? Does (b) -- a new-option request routing to question_queue.py -- actually exist as a real path, or could an agent currently just add a new option unilaterally?

### Judgment 4: VIP source handling must be careful
Two reasons: licensed assets shouldn't flood into context (.claudeignore must cover $DESIGNWARE_HOME), and full-text loading crowds out context that's actually needed. Approach: build a symbol index (class names, config field names, callback names -> file:line), then do a targeted ~30-line read only when a specific API behavior needs confirming.
Check: does a real .claudeignore exist and does it actually cover $DESIGNWARE_HOME (or an equivalent real VIP source path in this project)? Does any real symbol-indexing tool/artifact exist for VIP source (class/config-field/callback name -> file:line), or does the current implementation (if any) still read VIP source files in full when it needs API info?

Report your verdict per the required format for each of the 4 judgments separately.`, {label: 'audit:four-judgments', phase: 'Audit'})

const auditAuthorityOrder = agent(`${CORE_PRINCIPLES}

## Your scope: the 9-level conflict authority order

Hard-coded, so the agent never has to judge on the spot, exact order:
1. elaboration / actual simulation result
2. reference command.txt
3. DUT RTL
4. register file (DUT -> Global)
5. top testbench's existing bind
6. controller doc / programming guide
7. IP user guide
8. VIP example
9. VIP document

When a document and RTL disagree, the agent must NEVER pick a side on its own -- it must ALWAYS generate a question-queue entry with BOTH sides' evidence paths attached. Such disagreements are explicitly valuable findings in themselves -- often a real bug or a real stale doc.

Check: is this exact 9-level ordering written down anywhere as an explicit, hard-coded rule an agent actually follows (CLAUDE.md, a skill, or real code implementing a priority-resolution function)? Or does conflict resolution today happen ad hoc, with no fixed order? Separately: when reference_pattern_audit.py (or any other real tool) finds a doc/RTL mismatch, does it actually produce a question-queue entry with both evidence paths, or does it just report the mismatch as a text finding with no structured escalation?

Report your verdict per the required format for: the ordering itself (present/missing/partial), and the mismatch-escalates-to-question-queue-with-both-evidence-paths behavior.`, {label: 'audit:authority-order', phase: 'Audit'})

const auditContextBudget = agent(`${CORE_PRINCIPLES}

## Your scope: the 3-tier context budget rules

- NEVER into context: VIP source full text, raw PDF originals, whole-chip database, complete regression logs.
- ALWAYS resident: hierarchy.json summary layer, phy_boundary.json, run_profile.json, CLAUDE.md index.
- LOAD ON DEMAND: vip_ref/, intent.md, single regmap.json lookups.
- Everything routes through the MCP query interface discussed elsewhere -- the agent must never freely read files outside this discipline.

Check: is this 3-tier classification written down anywhere as an explicit rule (CLAUDE.md, a skill, or enforced by real tooling)? Is there any REAL enforcement mechanism (not just a documented intention) that would actually prevent an agent from, say, cat-ing a full VIP source file or a full regression log into its own context -- e.g. a .claudeignore, a lint/gate on agent tool-call patterns, or reliance purely on the MCP interface's own read-only/fixed-verb design making free reads structurally awkward? Be honest about whether this is a real, enforced discipline or currently just an aspirational principle no code actually checks.

Report your verdict per the required format for each of the 3 tiers and for the "everything through MCP" enforcement claim.`, {label: 'audit:context-budget', phase: 'Audit'})

const results = await parallel([
  () => auditAssetTable, () => auditFourJudgments, () => auditAuthorityOrder, () => auditContextBudget,
])
const [assetTableR, fourJudgmentsR, authorityOrderR, contextBudgetR] = results

phase('Close')

const auditSummaries = [
  ['Asset-processing table (14 rows: hierarchy/phy_boundary/regmap/sys_regmap/intent/init_seq/constraints/vip_ref/etc.)', assetTableR],
  ['4 key judgments (PHY-decides-bind, register-file division, command.txt authority, VIP-source symbol-indexing)', fourJudgmentsR],
  ['9-level conflict authority order + mismatch-to-question-queue escalation', authorityOrderR],
  ['3-tier context budget (never-load / resident / on-demand) + MCP-only enforcement', contextBudgetR],
]

log('Audit phase complete. Closing confirmed real BLOCKED gaps one at a time, sequentially, to avoid concurrent-edit collisions with the other workflows active in this session.')

const closeResults = []
for (const [name, report] of auditSummaries) {
  const fixResult = await agent(`Working directory: D:\\DV\\Task\\DV_Agent_Harness_L5\\v50

## Background

${CORE_PRINCIPLES}

This is a sequential gap-closing pass over a fresh re-verification of DV Agent Harness L5's asset-processing table / 4 key judgments / conflict authority order / context budget rules. You are handling exactly ONE scope: **${name}**.

NOTE: MANY other agents/workflows are concurrently active in this repo right now (a 14-AI-mechanism audit+close workflow, a governance-architecture reverify, an Obsidian-memory 25-phase reverify, a verification-knowledge-assets reverify, a self-describing-environment/bind-connectivity reverify, a live remote USB build). CLAUDE.md, connectivity.py, env_manifest.py, and reference_pattern_audit.py in particular are very likely being touched by several of those concurrently. Check git status/git diff on any file BEFORE touching it, and use the hand-scoped patch technique (git diff > patch, trim to your hunk, git apply --cached --check then --cached) for EVERY file, never a broad git add. If a file shows unexpected concurrent changes, re-read it fresh before patching, and re-diff after any conflict rather than forcing your original patch.

Its real, current audit finding (read carefully, this is real evidence gathered just now):

${report}

## Your task

1. For every requirement marked READY: do nothing, just re-confirm the cited evidence.
2. For every requirement marked BLOCKED (a real, closeable gap): build it for real, extending existing real code/artifacts (env_manifest.py, connectivity.py, run_profile_to_justfile.py, reference_pattern_audit.py, CLAUDE.md) rather than a parallel mechanism. Where the spec asks for a new artifact TYPE (e.g. phy_boundary.json, sys_regmap.json, intent.md, init_seq.yaml, constraints.md, vip_ref/, a VIP-source symbol indexer) that genuinely doesn't exist yet, build a real, minimal, working version -- a real extractor script + real schema + at least one real or synthetic worked example -- not just a stub.
3. For every requirement marked PARTIAL: complete the missing piece if genuinely bounded; if it's a large separate effort, report NEEDS_SEPARATE_EFFORT instead.
4. Write real tests proving whatever you build actually works.
5. Run the full relevant test suite for whatever you touched and confirm pass.
6. Commit your change for real (if you made one) with a clear, scoped commit.

Write a report to .work/gap-close-asset-table-${name.replace(/[^a-zA-Z0-9]+/g, '-').toLowerCase().slice(0, 40)}-report.md. Report DONE (with what changed) / NO_ACTION_NEEDED / NEEDS_SEPARATE_EFFORT / BLOCKED, with a one-line test summary if you made a change.`, {label: `close:${name}`, phase: 'Close', model: 'claude-opus-5'})
  closeResults.push([name, fixResult])
  log(`Closed pass done for ${name}.`)
}

phase('Report')

const finalReport = await agent(`${CORE_PRINCIPLES}

Independently review this "re-verify asset-processing table + 4 judgments + authority order + context budget + close every confirmed real gap" effort for DV Agent Harness L5. Do not accept any report's own claim without independent re-verification -- run real commands yourself.

Read every audit report and every close-pass report in full first (search .work/ for files matching gap-close-asset-table-*-report.md).

Raw returned results, for cross-reference:

### Audits
${auditSummaries.map(([name, report]) => `#### ${name}\n${report}`).join('\n\n')}

### Close-pass results
${closeResults.map(([name, result]) => `#### ${name}\n${result}`).join('\n\n')}

Verify independently:
1. For every close-pass reporting DONE: did the fix actually work, verified by you running something real (a real extractor script against a real or synthetic input, a real generated artifact)?
2. Run the full project test suite (python -m pytest dv_harness_tests/ -q) and report the real pass/fail count.
3. Check git hygiene across all commits this pass made -- pay special attention here since this workflow ran concurrently with several others touching overlapping files (CLAUDE.md, connectivity.py, env_manifest.py especially); confirm no commit accidentally swept in another workflow's unrelated in-progress changes, and confirm CLAUDE.md's current content is coherent (no duplicated or contradictory sections from concurrent edits).

Report a clear verdict per section (GENUINELY_CLOSED / STILL_GAP / CORRECTLY_DEFERRED) plus an overall verdict (APPROVED / NEEDS_FIX), with concrete evidence-cited findings.`, {label: 'final-report', phase: 'Report', model: 'claude-opus-5'})

return { auditSummaries: Object.fromEntries(auditSummaries), closeResults: Object.fromEntries(closeResults), finalReport }
