"""dv_harness/uvm_generator/pattern_registry_generator.py -- real pattern-suite
registry generation + Makefile dispatch, matching USB_UVM_Handoff's
tb/patterns/pattern_list.txt + generated dv_uvm_pattern_pool.svh mechanism.

BUG FIX (2026-08-29, 9-policy audit / USB regen-fidelity plan Phase 1 item 2):
the historical bug class this closes is real and observed in the catalogued
USB_UVM_Handoff package itself (3 real pattern .txt files present on disk but
absent from pattern_list.txt's registry, and a Makefile SUITE grouping that
must be re-derived, never hand-maintained, or a taxonomy migration silently
leaves a suite name matching zero patterns). `compute_suite_names` is always
recomputed from the actual pattern list -- never a separate hardcoded
constant -- and `build_registry` refuses to emit a registry with a declared
suite that resolves to zero patterns.
"""
from __future__ import annotations

from .generator import sv_id


class RegistryError(ValueError):
    def __init__(self, reason: str, detail: dict):
        super().__init__(reason)
        self.reason = reason
        self.detail = detail


def compute_suite_names(patterns):
    return sorted({p["suite"] for p in patterns})


def build_registry(patterns, declared_suites=None):
    """`patterns`: list of {"name", "suite", "dir", "file" (optional)} dicts.
    `declared_suites`, if given, is a fixed taxonomy (e.g. the Makefile's
    SUITE= choices) that every entry must actually have >=1 pattern for --
    this is the direct fix for the "hardcoded suite list silently matching
    zero patterns after migration" bug class."""
    seen = {}
    for p in patterns:
        name = p.get("name")
        if not name:
            raise RegistryError("MALFORMED_PATTERN_ENTRY", {"entry": p})
        if name in seen:
            raise RegistryError("DUPLICATE_PATTERN_NAME", {"name": name})
        if not p.get("suite"):
            raise RegistryError("MISSING_SUITE_DIR", {"name": name, "field": "suite"})
        if not p.get("dir"):
            raise RegistryError("MISSING_SUITE_DIR", {"name": name, "field": "dir"})
        seen[name] = p

    ordered = sorted(seen.values(), key=lambda pp: pp["name"])
    suite_names = compute_suite_names(ordered)
    declared = sorted(set(declared_suites)) if declared_suites is not None else list(suite_names)
    zero_pattern_suites = [s for s in declared if s not in suite_names]
    if zero_pattern_suites:
        raise RegistryError("SUITE_WITH_ZERO_PATTERNS", {"suites": zero_pattern_suites})

    return {"patterns": ordered, "suite_names": suite_names, "declared_suites": declared}


def emit_registry_txt(registry) -> str:
    lines = [
        f'{p["name"]} {p["suite"]} {p["dir"]}/{p.get("file", p["name"] + ".txt")}'
        for p in registry["patterns"]
    ]
    return "\n".join(lines) + ("\n" if lines else "")


def emit_pattern_pool_svh(registry) -> str:
    """Generated case-dispatcher task, `+PATTERN=` plusarg driven -- mirrors
    USB_UVM_Handoff's dv_uvm_pattern_pool.svh being a GENERATED (not
    hand-edited) file."""
    cases = "\n".join(
        f'    "{p["name"]}": run_{sv_id(p["name"])}();' for p in registry["patterns"]
    )
    return f"""// GENERATED by dv_harness/uvm_generator/pattern_registry_generator.py --
// regenerate from the current pattern registry; do not hand-edit.
task automatic run_selected_pattern(string pattern_name);
  case (pattern_name)
{cases}
    default: `uvm_fatal("PATTERN_POOL", $sformatf("Unknown pattern '%s' -- not in the generated registry", pattern_name))
  endcase
endtask
"""


def emit_makefile_fragment(registry_path) -> str:
    path = str(registry_path)
    return f"""# Generated by dv_harness/uvm_generator/pattern_registry_generator.py --
# hand-edit the pattern source list that feeds build_registry, not this
# target list.
PATTERN_REGISTRY_PATH := {path}

.PHONY: list_patterns add_pattern remove_pattern
list_patterns:
\t@cat $(PATTERN_REGISTRY_PATH)

add_pattern:
\t@test -n "$(PAT_NAME)" || (echo "PAT_NAME required" && exit 1)
\t@test -n "$(PAT_SUITE)" || (echo "PAT_SUITE required" && exit 1)
\t@test -n "$(PAT_DIR)" || (echo "PAT_DIR required" && exit 1)
\t@cp $(PATTERN_REGISTRY_PATH) $(PATTERN_REGISTRY_PATH).bak
\t@echo "$(PAT_NAME) $(PAT_SUITE) $(PAT_DIR)/$(PAT_NAME).txt" >> $(PATTERN_REGISTRY_PATH)

remove_pattern:
\t@test -n "$(PAT_NAME)" || (echo "PAT_NAME required" && exit 1)
\t@cp $(PATTERN_REGISTRY_PATH) $(PATTERN_REGISTRY_PATH).bak
\t@grep -v "^$(PAT_NAME) " $(PATTERN_REGISTRY_PATH) > $(PATTERN_REGISTRY_PATH).tmp && mv $(PATTERN_REGISTRY_PATH).tmp $(PATTERN_REGISTRY_PATH)
"""
