"""dv_harness/uvm_generator/regression_list_manager.py -- executable bookkeeping
for CLAUDE.md's "LSF DONE is not equal to DV PASS" rule.

BUG FIX (2026-08-29, 9-policy audit): the USB_UVM_Handoff catalog (sim/scripts/
Makefile's regression.list handling) showed a real pattern this harness had no
equivalent for -- a durable, on-disk record of which patterns have CURRENTLY
verified PASS, that a stale/failed rerun automatically evicts from. Without
this, a regression.list can silently keep crediting a pattern that failed on
its most recent run (an LSF job completing -- DONE -- proves nothing about
whether the testcase actually PASSed).

File format: one passing pattern name per line, no PASS/FAIL suffix -- a
pattern's mere presence in the file IS the "currently verified PASS" claim.
This deliberately keeps the on-disk format `grep`/`comm`-friendly (matching
the real Makefile's own tool-driven bookkeeping style) and makes "did this
pattern regress" a plain `grep -xF <pattern> regression.list` check.
"""
from __future__ import annotations

from collections import OrderedDict
from pathlib import Path


def record_verdict(existing_lines, pattern: str, verdict_passed: bool):
    """Idempotent grep -vxF <pattern> + conditional re-add: removes any prior
    entry for `pattern` regardless of its old verdict, then re-adds it only if
    `verdict_passed`. A FAIL therefore always evicts a stale PASS; a repeated
    PASS is a no-op (same final list either way)."""
    if not pattern:
        raise ValueError("pattern must be a non-empty string")
    filtered = [ln for ln in existing_lines if ln != pattern]
    if verdict_passed:
        filtered.append(pattern)
    return filtered


def apply_verdict_to_file(regression_list_path, pattern: str, verdict_passed: bool) -> None:
    """File-I/O wrapper around the pure record_verdict() -- reads the current
    regression.list (missing file treated as empty, matching a project's
    first-ever recorded pattern), applies record_verdict(), writes back.
    record_verdict() itself is unchanged and untouched by this wrapper.

    File format uses LF line endings (\\n only, never \\r\\n) to stay
    grep/comm-friendly for the real Linux-side Makefile."""
    path = Path(regression_list_path)
    if path.exists():
        with path.open("r", encoding="utf-8", newline="") as f:
            existing = f.read().splitlines()
    else:
        existing = []
    updated = record_verdict(existing, pattern, verdict_passed)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(updated) + ("\n" if updated else ""))


def record_suite(existing_lines, verdicts):
    """Single-pass equivalent of calling record_verdict once per (pattern,
    passed) pair in `verdicts`, in order -- including when the same pattern
    appears more than once (last verdict wins), without rescanning the
    growing list once per verdict the way N sequential record_verdict calls
    would."""
    touched = OrderedDict()
    for pattern, passed in verdicts:
        if not pattern:
            raise ValueError("pattern must be a non-empty string")
        if pattern in touched:
            del touched[pattern]
        touched[pattern] = passed
    unchanged = [ln for ln in existing_lines if ln not in touched]
    newly_passed = [p for p, passed in touched.items() if passed]
    return unchanged + newly_passed


def emit_makefile_fragment(regression_list_path) -> str:
    path = str(regression_list_path)
    return f"""# Generated by dv_harness/uvm_generator/regression_list_manager.py --
# hand-edit the JSON/CLI inputs that feed record_verdict/record_suite, not
# this target list.
REGRESSION_LIST_PATH := {path}

.PHONY: regression-list-show regression-list-clean
regression-list-show:
\t@test -f $(REGRESSION_LIST_PATH) && cat $(REGRESSION_LIST_PATH) || echo "(no regression list yet at $(REGRESSION_LIST_PATH))"

regression-list-clean:
\trm -f $(REGRESSION_LIST_PATH)
"""
