"""Generate a `justfile` from a validated run_profile.json.

Purpose (per the asset-processing design in docs/RUN_PROFILE.md): the
generated justfile is the ONLY execution surface an agent may call for this
environment. Every recipe forwards to `make` using exactly the variable
names captured in run_profile.json -- never a hand-composed vcs/simv command
line -- and every recipe validates its arguments against the profile's own
enum/retired constraints BEFORE shelling out, so an invalid combination
fails fast with the source Makefile's own $(error) text instead of vcs
failing deep, or a knob being silently ignored.

A modeled recipe missing an option an agent believes it needs is a
question-queue item, not a reason to hand-edit this file or fall back to
`make` directly -- see the `human_raw_override` recipe's own warning
comment for the one sanctioned human-only escape hatch.
"""
from __future__ import annotations

import shutil
import sys
from pathlib import Path

from dv_harness.uvm_generator.run_profile import (
    RunProfileValidationError,
    check_constraints,
    find_param,
    load_run_profile,
)

_STANDALONE_VALIDATOR_TEMPLATE = (
    Path(__file__).resolve().parent / "templates" / "sim_scripts" / "validate_run_profile_args.py"
)

# Targets this generator knows how to build a real recipe for. Any other
# target present in the profile's `targets` list still gets a bare
# passthrough recipe (no typed params, no validation) -- present because it
# is real, not because this generator understands it.
_MODELED_TARGETS = {"compile", "sim", "regress", "check", "clean", "distclean", "list_patterns", "help"}


def _param_summary(profile: dict, name: str) -> str:
    """One-line 'NAME (=default, enum: a|b|c)' summary for the comment above
    a recipe -- documentation only, never interpolated into the recipe body.
    Real defaults stay owned by the source Makefile's own `?=`; duplicating
    them as just parameter defaults was tried and rejected (see the design
    note on `*args` passthrough below) because just recipe parameters are
    POSITIONAL, not KEY=value, which silently mismatches make's own
    KEY=value convention -- confirmed by a real `just --dry-run` run
    producing `SPEED=speed=gen1` instead of `SPEED=gen1`.
    """
    param = find_param(profile, name)
    if not param:
        return name
    bits = [name]
    if param.get("default") not in (None, ""):
        bits.append(f"={param['default']}")
    if param.get("type") == "enum" and param.get("enum"):
        bits.append(f" [{'|'.join(param['enum'])}]")
    return "".join(bits)


def generate_justfile(profile: dict) -> str:
    source = profile["source"]
    lines: list[str] = []
    lines.append("# AUTO-GENERATED by dv_harness.uvm_generator.run_profile_to_justfile")
    lines.append(f"# Source of truth: {source['path']}")
    if source.get("content_sha256"):
        lines.append(f"# Source sha256 at extraction time: {source['content_sha256']}")
    lines.append(
        "# DO NOT hand-edit the recipes below. Re-run the extractor against the real "
        "source and regenerate this file. An agent that wants a knob not listed here "
        "must raise it via the question queue -- it may never add one itself."
    )
    lines.append("")
    lines.append('set shell := ["bash", "-uc"]')
    lines.append("")
    lines.append('_profile := "run_profile.json"')
    lines.append("")
    lines.append(
        "# Validates one target's args against run_profile.json's own enum/retired "
        "constraints before make ever runs. Fails fast with the source's own $(error) "
        "message rather than letting an invalid combination reach vcs. Deliberately a "
        "standalone stdlib-only script, not `python3 -m dv_harness...` -- this "
        "environment ships to a DV team that does not necessarily have the Harness "
        "package installed alongside it. Plain relative paths, not "
        "{{justfile_directory()}} -- interpolating an absolute Windows path through "
        "`set shell := [\"bash\", \"-uc\"]` mangles the backslashes (confirmed by a real "
        "run); this justfile is always invoked from its own directory like every other "
        "recipe here that references run_profile.json the same way."
    )
    lines.append("_validate target *args:")
    lines.append('\t@python3 validate_run_profile_args.py {{_profile}} {{target}} {{args}}')
    lines.append("")

    for target in profile.get("targets", []):
        name = target["name"]
        if name not in _MODELED_TARGETS:
            continue
        desc = target.get("description", "")
        params: list[str] = target.get("params", [])
        recipe_name = name.replace("_", "-")

        if desc:
            lines.append(f"# {desc}")
        if target.get("requires_rebuild"):
            lines.append("# Changing any variable below requires a rebuild (this target itself IS the rebuild).")

        if not params:
            lines.append(f"{recipe_name}:")
            lines.append(f"\tmake {name}")
            lines.append("")
            continue

        # *args (variadic passthrough), NOT typed named parameters: just
        # recipe parameters are positional, so `just compile speed=gen1`
        # would bind the ENTIRE literal token "speed=gen1" to just's first
        # positional parameter rather than reading it as KEY=value the way
        # `make compile SPEED=gen1` does -- confirmed by a real
        # `just --dry-run` run before this design was adopted. Passthrough
        # keeps the real Makefile variable names as the actual interface,
        # keeps defaults owned by the Makefile's own `?=` (never duplicated
        # here), and still restricts an agent to real make VAR=value pairs
        # for a real, allow-listed target -- it can never invoke an
        # unmodeled make target this way, only unmodeled variables on a
        # modeled one, which _validate still catches for anything with a
        # known constraint.
        var_summary = "  ".join(_param_summary(profile, p) for p in params)
        lines.append(f"# vars: {var_summary}")
        lines.append(f"{recipe_name} *args:")
        lines.append(f"\t@just _validate {name} {{{{args}}}}")
        lines.append(f"\tmake {name} {{{{args}}}}")
        lines.append("")

    lines.append(
        "# HUMAN OVERRIDE ONLY. An agent calling this instead of a modeled recipe above "
        "is bypassing the reason run_profile.json exists. If a modeled recipe is missing "
        "a real option, that is a question-queue item, never a reason to use this."
    )
    lines.append("human_raw_override target *args:")
    lines.append("\tmake {{target}} {{args}}")
    lines.append("")

    return "\n".join(lines) + "\n"


def copy_standalone_validator(out_dir: Path) -> Path:
    """Copy the dependency-free validator script next to a generated
    justfile. Must be called whenever a justfile is generated for a real
    (non-scratch) environment -- the `_validate` recipe references this
    file by relative path and has no fallback.
    """
    dest = out_dir / _STANDALONE_VALIDATOR_TEMPLATE.name
    shutil.copyfile(_STANDALONE_VALIDATOR_TEMPLATE, dest)
    return dest


def generate_and_write(profile_path: Path, out_path: Path, copy_validator: bool = True) -> str:
    profile = load_run_profile(profile_path)
    text = generate_justfile(profile)
    out_path.write_text(text, encoding="utf-8")
    if copy_validator:
        copy_standalone_validator(out_path.parent)
    return text


def _cli_validate(argv: list[str]) -> int:
    if len(argv) < 2:
        print("usage: validate <run_profile.json> <target> [KEY=VALUE ...]", file=sys.stderr)
        return 2
    profile_path, target = argv[0], argv[1]
    kv_args = argv[2:]
    values: dict[str, str] = {}
    for arg in kv_args:
        if "=" not in arg:
            continue
        key, _, val = arg.partition("=")
        if val != "":
            values[key] = val

    try:
        profile = load_run_profile(Path(profile_path))
    except RunProfileValidationError as exc:
        print(f"run_profile.json is invalid, refusing to validate against it:\n{exc}", file=sys.stderr)
        return 2

    violations = check_constraints(profile, values)

    for constraint in profile.get("constraints", []):
        if constraint["kind"] != "retired":
            continue
        for retired_name in constraint["params"]:
            if retired_name in values:
                violations.append(f"{retired_name}={values[retired_name]!r}: {constraint['message']}")

    if violations:
        print(f"Rejected args for target '{target}':", file=sys.stderr)
        for v in violations:
            print(f"  - {v}", file=sys.stderr)
        return 1
    return 0


def main(argv: list[str] | None = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    if not argv:
        print("usage: run_profile_to_justfile.py {generate|validate} ...", file=sys.stderr)
        return 2
    cmd, rest = argv[0], argv[1:]
    if cmd == "validate":
        return _cli_validate(rest)
    if cmd == "generate":
        if len(rest) < 2:
            print("usage: generate <run_profile.json> <out justfile path>", file=sys.stderr)
            return 2
        generate_and_write(Path(rest[0]), Path(rest[1]))
        return 0
    print(f"unknown subcommand: {cmd}", file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
