// GENERATED by dv_harness/uvm_generator/pattern_registry_generator.py --
// regenerate from the current pattern registry; do not hand-edit.
task automatic run_selected_pattern(string pattern_name);
  case (pattern_name)
    "USB2_con_vip": run_usb2_con_vip();
    default: `uvm_fatal("PATTERN_POOL", $sformatf("Unknown pattern '%s' -- not in the generated registry", pattern_name))
  endcase
endtask
