# Generated by dv_harness/uvm_generator/pattern_registry_generator.py --
# hand-edit the pattern source list that feeds build_registry, not this
# target list.
PATTERN_REGISTRY_PATH := examples\generated_usb_real_evidence_v1\patterns_registry\pattern_list.txt

.PHONY: list_patterns add_pattern remove_pattern
list_patterns:
	@cat $(PATTERN_REGISTRY_PATH)

add_pattern:
	@test -n "$(PAT_NAME)" || (echo "PAT_NAME required" && exit 1)
	@test -n "$(PAT_SUITE)" || (echo "PAT_SUITE required" && exit 1)
	@test -n "$(PAT_DIR)" || (echo "PAT_DIR required" && exit 1)
	@cp $(PATTERN_REGISTRY_PATH) $(PATTERN_REGISTRY_PATH).bak
	@echo "$(PAT_NAME) $(PAT_SUITE) $(PAT_DIR)/$(PAT_NAME).txt" >> $(PATTERN_REGISTRY_PATH)

remove_pattern:
	@test -n "$(PAT_NAME)" || (echo "PAT_NAME required" && exit 1)
	@cp $(PATTERN_REGISTRY_PATH) $(PATTERN_REGISTRY_PATH).bak
	@grep -v "^$(PAT_NAME) " $(PATTERN_REGISTRY_PATH) > $(PATTERN_REGISTRY_PATH).tmp && mv $(PATTERN_REGISTRY_PATH).tmp $(PATTERN_REGISTRY_PATH)
