`ifndef GUARD_CUST_AXI_MASTER_SEQUENCE_COLLECTION_SV
`define GUARD_CUST_AXI_MASTER_SEQUENCE_COLLECTION_SV

/**
 * Abstract:
 * cust_axi_master_directed_4kboundary_sequence is used by test to provide initiator
 * scenario information to the Master agent present in the System Env.
 * This class defines a sequence in which a AXI WRITE followed by a AXI READ
 * sequence is generated by assigning values to the transactions rather than
 * randomization, and then transmitted using `uvm_send.
 *
 * Execution phase: main_phase
 * Sequencer: Master agent sequencer
 */

class cust_axi_master_directed_4kboundary_sequence extends svt_axi_master_base_sequence;

  /** Parameter that controls the number of transactions that will be generated */
  rand int unsigned sequence_length = 10;

  /** Constrain the sequence length to a reasonable value */
  constraint reasonable_sequence_length {
    sequence_length <= 100;
  }

  /** UVM Object Utility macro */
  `uvm_object_utils(cust_axi_master_directed_4kboundary_sequence)

  /** Class Constructor */
  function new(string name="cust_axi_master_directed_4kboundary_sequence");
    super.new(name);
  endfunction
  
  virtual task body();
    svt_axi_master_transaction write_tran, read_tran;
    svt_configuration get_cfg;
    bit status;
    `uvm_info("body", "Entered ...", UVM_LOW)

    super.body();

    status = uvm_config_db #(int unsigned)::get(null, get_full_name(), "sequence_length", sequence_length);
    `uvm_info("body", $sformatf("sequence_length is %0d as a result of %0s.", sequence_length, status ? "config DB" : "randomization"), UVM_LOW);

    /** Obtain a handle to the port configuration */
    p_sequencer.get_cfg(get_cfg);
    if (!$cast(cfg, get_cfg)) begin
      `uvm_fatal("body", "Unable to $cast the configuration to a svt_axi_port_configuration class");
    end

    for(int i = 0; i < sequence_length; i++) begin

      /** Set up the write transaction */
      `uvm_create(write_tran)
      write_tran.port_cfg     = cfg;
      write_tran.xact_type    = svt_axi_transaction::WRITE;
      write_tran.addr         = 32'h0fff_f8fe | ('h100 << i);
      write_tran.burst_type   = svt_axi_transaction::INCR;
      write_tran.burst_size   = svt_axi_transaction::BURST_SIZE_32BIT;
      write_tran.atomic_type  = svt_axi_transaction::NORMAL;
`ifdef SVT_AXI_MAX_BURST_LENGTH_WIDTH_1
      write_tran.burst_length = 1;
`elsif SVT_AXI_MAX_BURST_LENGTH_WIDTH_2
      write_tran.burst_length = 2;
`elsif SVT_AXI_MAX_BURST_LENGTH_WIDTH_3
      write_tran.burst_length = 4;
`elsif SVT_AXI_MAX_BURST_LENGTH_WIDTH_4
      write_tran.burst_length = 8;
`else
      write_tran.burst_length = 16;
`endif      
      write_tran.data         = new[write_tran.burst_length];
      write_tran.wstrb        = new[write_tran.burst_length];
      write_tran.data_user    = new[write_tran.burst_length];
      foreach (write_tran.data[i]) begin
        write_tran.data[i] = i;
      end
      foreach(write_tran.wstrb[i]) begin
        write_tran.wstrb[i] = 4'hf;
      end
      write_tran.wvalid_delay = new[write_tran.burst_length];
      foreach (write_tran.wvalid_delay[i]) begin
        write_tran.wvalid_delay[i]=i;
      end

      /** Send the write transaction */
      `uvm_send(write_tran)

      /** Wait for the write transaction to complete */
      get_response(rsp);

      `uvm_info("body", "AXI WRITE transaction completed", UVM_LOW);

      /** Set up the read transaction */
      `uvm_create(read_tran)
      read_tran.port_cfg     = cfg;
      read_tran.xact_type    = svt_axi_transaction::READ;
      read_tran.addr         = 32'h0fff_f8fe | ('h100 << i);
      read_tran.burst_type   = svt_axi_transaction::INCR;
      read_tran.burst_size   = svt_axi_transaction::BURST_SIZE_32BIT;
      read_tran.atomic_type  = svt_axi_transaction::NORMAL;
`ifdef SVT_AXI_MAX_BURST_LENGTH_WIDTH_1
      read_tran.burst_length = 1;
`elsif SVT_AXI_MAX_BURST_LENGTH_WIDTH_2
      read_tran.burst_length = 2;
`elsif SVT_AXI_MAX_BURST_LENGTH_WIDTH_3
      read_tran.burst_length = 4;
`elsif SVT_AXI_MAX_BURST_LENGTH_WIDTH_4
      read_tran.burst_length = 8;
`else
      read_tran.burst_length = 16;
`endif      
      read_tran.rresp        = new[read_tran.burst_length];
      read_tran.data         = new[read_tran.burst_length];
      read_tran.rready_delay = new[read_tran.burst_length];
      read_tran.data_user    = new[read_tran.burst_length];
      foreach (read_tran.rready_delay[i]) begin
        read_tran.rready_delay[i]=i;
      end

      /** Send the read transaction */
      `uvm_send(read_tran)

      /** Wait for the read transaction to complete */
      get_response(rsp);
    
      `uvm_info("body", "AXI READ transaction completed", UVM_LOW);
    end

    `uvm_info("body", "Exiting...", UVM_LOW)
  endtask: body
virtual task post_body();
 super.post_body();
  if (`SVT_AXI_TRANSACTION_ADDR_RANGE_NUM_LSB_BITS >12 && `SVT_AXI_TRANSACTION_4K_ADDR_RANGE > 4096) begin 
     `uvm_info("post_body", $sformatf("SVT_AXI_TRANSACTION_ADDR_RANGE_NUM_LSB_BITS is %0d and SVT_AXI_TRANSACTION_4K_ADDR_RANGE is %d  ", `SVT_AXI_TRANSACTION_ADDR_RANGE_NUM_LSB_BITS, `SVT_AXI_TRANSACTION_4K_ADDR_RANGE ), UVM_LOW);

end 
else if (`SVT_AXI_TRANSACTION_ADDR_RANGE_NUM_LSB_BITS  <= 12 && `SVT_AXI_TRANSACTION_4K_ADDR_RANGE <= 4096) begin 
     `uvm_info("post_body", $sformatf("SVT_AXI_TRANSACTION_ADDR_RANGE_NUM_LSB_BITS is %d and SVT_AXI_TRANSACTION_4K_ADDR_RANGE is %d ", `SVT_AXI_TRANSACTION_ADDR_RANGE_NUM_LSB_BITS, `SVT_AXI_TRANSACTION_4K_ADDR_RANGE), UVM_LOW);

end 
else begin 
     `uvm_error ("post_body"," The 4K boundary crossing values are inconsistent");
  end
endtask

endclass: cust_axi_master_directed_4kboundary_sequence

/**
 * Abstract:
 * cust_axi_master_directed_sequence is used by test to provide initiator
 * scenario information to the Master agent present in the System Env.
 * This class defines a sequence in which a AXI WRITE followed by a AXI READ
 * sequence is generated by assigning values to the transactions rather than
 * randomization, and then transmitted using `uvm_send.
 *
 * Execution phase: main_phase
 * Sequencer: Master agent sequencer
 */


class cust_axi_master_directed_sequence extends svt_axi_master_base_sequence;

  /** Parameter that controls the number of transactions that will be generated */
  rand int unsigned sequence_length = 10;

  /** Constrain the sequence length to a reasonable value */
  constraint reasonable_sequence_length {
    sequence_length <= 100;
  }

  /** UVM Object Utility macro */
  `uvm_object_utils(cust_axi_master_directed_sequence)

  /** Class Constructor */
  function new(string name="cust_axi_master_directed_sequence");
    super.new(name);
  endfunction
  
  virtual task body();
    svt_axi_master_transaction write_tran, read_tran;
    svt_configuration get_cfg;
    bit status;
    `uvm_info("body", "Entered ...", UVM_LOW)

    super.body();

    status = uvm_config_db #(int unsigned)::get(null, get_full_name(), "sequence_length", sequence_length);
    `uvm_info("body", $sformatf("sequence_length is %0d as a result of %0s.", sequence_length, status ? "config DB" : "randomization"), UVM_LOW);

    /** Obtain a handle to the port configuration */
    p_sequencer.get_cfg(get_cfg);
    if (!$cast(cfg, get_cfg)) begin
      `uvm_fatal("body", "Unable to $cast the configuration to a svt_axi_port_configuration class");
    end

    for(int i = 0; i < sequence_length; i++) begin

      /** Set up the write transaction */
      `uvm_create(write_tran)
      write_tran.port_cfg     = cfg;
      write_tran.xact_type    = svt_axi_transaction::WRITE;
      write_tran.addr         = 32'h0000_0100 | ('h100 << i);
      write_tran.burst_type   = svt_axi_transaction::INCR;
      write_tran.burst_size   = svt_axi_transaction::BURST_SIZE_32BIT;
      write_tran.atomic_type  = svt_axi_transaction::NORMAL;
`ifdef SVT_AXI_MAX_BURST_LENGTH_WIDTH_1
      write_tran.burst_length = 1;
`elsif SVT_AXI_MAX_BURST_LENGTH_WIDTH_2
      write_tran.burst_length = 2;
`elsif SVT_AXI_MAX_BURST_LENGTH_WIDTH_3
      write_tran.burst_length = 4;
`elsif SVT_AXI_MAX_BURST_LENGTH_WIDTH_4
      write_tran.burst_length = 8;
`else
      write_tran.burst_length = 16;
`endif      
      write_tran.data         = new[write_tran.burst_length];
      write_tran.wstrb        = new[write_tran.burst_length];
      write_tran.data_user    = new[write_tran.burst_length];
      foreach (write_tran.data[i]) begin
        write_tran.data[i] = i;
      end
      foreach(write_tran.wstrb[i]) begin
        write_tran.wstrb[i] = 4'hf;
      end
      write_tran.wvalid_delay = new[write_tran.burst_length];
      foreach (write_tran.wvalid_delay[i]) begin
        write_tran.wvalid_delay[i]=i;
      end

      /** Send the write transaction */
      `uvm_send(write_tran)

      /** Wait for the write transaction to complete */
      get_response(rsp);

      `uvm_info("body", "AXI WRITE transaction completed", UVM_LOW);

      /** Set up the read transaction */
      `uvm_create(read_tran)
      read_tran.port_cfg     = cfg;
      read_tran.xact_type    = svt_axi_transaction::READ;
      read_tran.addr         = 32'h0000_0100 | ('h100 << i);
      read_tran.burst_type   = svt_axi_transaction::INCR;
      read_tran.burst_size   = svt_axi_transaction::BURST_SIZE_32BIT;
      read_tran.atomic_type  = svt_axi_transaction::NORMAL;
`ifdef SVT_AXI_MAX_BURST_LENGTH_WIDTH_1
      read_tran.burst_length = 1;
`elsif SVT_AXI_MAX_BURST_LENGTH_WIDTH_2
      read_tran.burst_length = 2;
`elsif SVT_AXI_MAX_BURST_LENGTH_WIDTH_3
      read_tran.burst_length = 4;
`elsif SVT_AXI_MAX_BURST_LENGTH_WIDTH_4
      read_tran.burst_length = 8;
`else
      read_tran.burst_length = 16;
`endif      
      read_tran.rresp        = new[read_tran.burst_length];
      read_tran.data         = new[read_tran.burst_length];
      read_tran.rready_delay = new[read_tran.burst_length];
      read_tran.data_user    = new[read_tran.burst_length];
      foreach (read_tran.rready_delay[i]) begin
        read_tran.rready_delay[i]=i;
      end

      /** Send the read transaction */
      `uvm_send(read_tran)

      /** Wait for the read transaction to complete */
      get_response(rsp);
    
      `uvm_info("body", "AXI READ transaction completed", UVM_LOW);
    end

    `uvm_info("body", "Exiting...", UVM_LOW)
  endtask: body

endclass: cust_axi_master_directed_sequence

/**
 * Abstract:
 * class cust_axi_master_random_discrete_sequence defines a sequence that generates a
 * random discrete master transaction.  This sequence is used by the
 * axi_master_random_discrete_virtual_sequence which is set up as the default
 * sequence for this environment.
 *
 * Execution phase: main_phase
 * Sequencer: Virtual sequencer in AXI System ENV
 */

class cust_axi_master_random_discrete_sequence extends svt_axi_master_base_sequence;

   /** Parameter that controls the number of transactions that will be generated */
   rand int unsigned sequence_length = 10;

  /** UVM Object Utility macro */
  `uvm_object_utils(cust_axi_master_random_discrete_sequence)

  /** Constrain the sequence length to a reasonable value */
  constraint reasonable_sequence_length {
    sequence_length <= 100;
  }

  /** Class Constructor */
  function new (string name = "cust_axi_master_random_discrete_sequence");
     super.new(name);
  endfunction : new

  virtual task body();
    bit status;

    `uvm_info("body", "Entered ...", UVM_LOW)

    status = uvm_config_db#(int unsigned)::get(null, get_full_name(), "sequence_length", sequence_length);
    `uvm_info("body", $sformatf("sequence_length is %0d as a result of %0s.", sequence_length, status ? "config DB" : "randomization"), UVM_LOW);

    for(int i = 0; i < sequence_length; i++) begin
      `uvm_info("body", $sformatf("Calling `uvm_do, iteration=%0d", i), UVM_LOW)
      `uvm_do(req)
    end

    `uvm_info("body", "Exiting...", UVM_LOW)
  endtask: body
  
endclass: cust_axi_master_random_discrete_sequence


/**
 * Abstract:
 * cust_axi_master_wr_rd_reorder_sequence is used by test to provide initiator scenario
 * information to the Master agent present in the System agent.  This class
 * defines a sequence in which AXI WRITE sequence and READ sequence
 * is generated using `uvm_do_with macros.
 *
 * Execution phase: main_phase
 * Sequencer: Master agent sequencer
 */


class cust_axi_master_wr_rd_reorder_sequence extends svt_axi_master_base_sequence;

  /** Parameter that controls the number of transactions that will be generated */
  rand int unsigned sequence_length = 10;

  /** Constrain the sequence length to a reasonable value */
  constraint reasonable_sequence_length {
    sequence_length <= 100;
  }

  /** UVM Object Utility macro */
  `uvm_object_utils(cust_axi_master_wr_rd_reorder_sequence)

  svt_axi_master_transaction write_tran[$],read_tran[$];

  /** Class Constructor */
  function new(string name="cust_axi_master_wr_rd_reorder_sequence");
    super.new(name);
  endfunction
  
  virtual task body();
    bit status;
    `uvm_info("body", "Entered ...", UVM_LOW)

    super.body();

    status = uvm_config_db #(int unsigned)::get(null, get_full_name(), "sequence_length", sequence_length);
    `uvm_info("body", $sformatf("sequence_length is %0d as a result of %0s.", sequence_length, status ? "config DB" : "randomization"), UVM_LOW);

    fork
    forever begin
      get_response(rsp);
    end
    join_none
    
    for (int i = 0;i < sequence_length;i++) begin
      `ifndef SVT_UVM_1800_2_2017_OR_HIGHER 
        `uvm_do_with(write_tran[i], 
        { 
          xact_type == svt_axi_transaction::WRITE;
          if (i == 0) {
            id == 0;
          }
          else {
            id == 1;
          }  
          addr_valid_delay == 0; 
          data_before_addr == 0;
          burst_type   == svt_axi_transaction::INCR;
          bready_delay == 0;
          foreach(wvalid_delay[ix]) {
            wvalid_delay[ix] == 0;
          }
        })
      `else 
        `uvm_do(write_tran[i],,, 
        { 
          xact_type == svt_axi_transaction::WRITE;
          if (i == 0) {
            id == 0;
          }
          else {
            id == 1;
          }  
          addr_valid_delay == 0; 
          data_before_addr == 0;
          burst_type   == svt_axi_transaction::INCR;
          bready_delay == 0;
          foreach(wvalid_delay[ix]) {
            wvalid_delay[ix] == 0;
          }
        })
      `endif
    end 
    for (int i = 0;i <sequence_length;i++) begin 
      write_tran[i].wait_for_transaction_end();
    end  
    
    for (int x = 0;x < sequence_length;x++) begin 
      `ifndef SVT_UVM_1800_2_2017_OR_HIGHER 
        `uvm_do_with(read_tran[x], 
        { 
          xact_type == svt_axi_transaction::READ;
          if (x == 0) {
            id == 10;
          }
          else {
            id == 20;
          } 
          addr_valid_delay == 0; 
          data_before_addr == 0;
          foreach(rready_delay[i]) {
            rready_delay[i] == 0;
          }  
        })
      `else 
        `uvm_do(read_tran[x],,, 
        { 
          xact_type == svt_axi_transaction::READ;
          if (x == 0) {
            id == 10;
          }
          else {
            id == 20;
          } 
          addr_valid_delay == 0; 
          data_before_addr == 0;
          foreach(rready_delay[i]) {
            rready_delay[i] == 0;
          }  
        })
      `endif
    end
    for (int x = 0;x <sequence_length;x++) begin 
      read_tran[x].wait_for_transaction_end();
    end  

    `uvm_info("body", "Exiting...", UVM_LOW)
  endtask: body

endclass: cust_axi_master_wr_rd_reorder_sequence

/**
 * Abstract:
 * cust_axi_master_wr_rd_sequence is used by test to provide initiator scenario
 * information to the Master agent present in the System agent.  This class
 * defines a sequence in which a random AXI WRITE followed by a random AXI READ
 * sequence is generated using `uvm_do_with macros.
 *
 * Execution phase: main_phase
 * Sequencer: Master agent sequencer
 */

class cust_axi_master_wr_rd_sequence extends svt_axi_master_base_sequence;

  /** Parameter that controls the number of transactions that will be generated */
  rand int unsigned sequence_length = 10;

  /** Constrain the sequence length to a reasonable value */
  constraint reasonable_sequence_length {
    sequence_length <= 100;
  }

  /** UVM Object Utility macro */
  `uvm_object_utils(cust_axi_master_wr_rd_sequence)

  /** Class Constructor */
  function new(string name="cust_axi_master_wr_rd_sequence");
    super.new(name);
  endfunction
  
  virtual task body();
    bit status;
    `uvm_info("body", "Entered ...", UVM_LOW)

    super.body();

    status = uvm_config_db #(int unsigned)::get(null, get_full_name(), "sequence_length", sequence_length);
    `uvm_info("body", $sformatf("sequence_length is %0d as a result of %0s.", sequence_length, status ? "config DB" : "randomization"), UVM_LOW);

    fork
    forever begin
      get_response(rsp);
    end
    join_none
    
    repeat (sequence_length) begin
      `ifndef SVT_UVM_1800_2_2017_OR_HIGHER
        `uvm_do_with(req, 
        { 
          xact_type == svt_axi_transaction::WRITE;
          data_before_addr == 0;
        })
      `else
       `uvm_do(req,,, 
        { 
          xact_type == svt_axi_transaction::WRITE;
          data_before_addr == 0;
        })
      `endif
      `ifndef SVT_UVM_1800_2_2017_OR_HIGHER
        `uvm_do_with(req, 
        { 
          xact_type == svt_axi_transaction::READ;
          data_before_addr == 0;
        })
      `else 
        `uvm_do(req,,, 
        { 
          xact_type == svt_axi_transaction::READ;
          data_before_addr == 0;
        })
      `endif
    end

    `uvm_info("body", "Exiting...", UVM_LOW)
  endtask: body

endclass: cust_axi_master_wr_rd_sequence

/**
 * Abstract:
 * class cust_axi_null_virtual_sequence defines a virtual sequence cust_axi_null_virtual_sequence.
 * cust_axi_null_virtual_sequence is a no-operation sequence since the body() method
 * has empty implementation.
 *
 * cust_axi_null_virtual_sequence is used by directed_test and random_wr_rd_test.
 * These tests load this null sequence into the virtual sequencer in testbench
 * ENV, as these tests use the sequencer in the master agent.
 *
 * Execution phase: main_phase 
 * Sequencer: Can be used with any sequencer in
 * which default sequence needs to be overridden with a null sequence. In this
 * example, this sequence has been used with virtual sequencer in the testbench
 * environment.
 */


class cust_axi_null_virtual_sequence extends uvm_sequence;

  /** UVM Object Utility macro */
  `uvm_object_utils(cust_axi_null_virtual_sequence)

  /** Class Constructor */
  function new (string name = "cust_axi_null_virtual_sequence");
     super.new(name);
  endfunction : new

  /** Need an empty body function to override the warning from the UVM base class */
  virtual task body();
  endtask

endclass : cust_axi_null_virtual_sequence 

`endif // GUARD_CUST_AXI_MASTER_SEQUENCE_COLLECTION_SV
