"""Tests for SYS-9..SYS-14 of the System-Level Verification Integration
workflow: `dv_harness/system_resource_inventory.py` and the one primitive it
needed from `dv_harness/connectivity.py`
(`find_active_bind_target_collisions()`).

EVERY fixture is SYNTHETIC and built inside a tmp_path: fake connectivity
matrices, fake env.manifest.json files (real, schema-valid, generated by the
real `env_manifest.generate_and_write()`), a fake vip_config dump, a fake SoC
architecture map with deliberately overlapping address ranges, a fake registry.
Nothing touches the real
`.dv-harness/soc-composer/subsystem_environment_registry.json` (legitimately
absent in this repo), and no test generates System-Level UVM source, a System
command.txt, a shared agent or a virtual sequencer -- SYS-9..14 is
discovery/analysis/planning/reporting only, and three tests assert that rather
than trusting it.

The suite is deliberately not a happy path. A dedup/conflict mechanism whose
only coverage is the case where everything agrees has no detection power, so
the cases that carry this suite are the ambiguous and conflicting ones:

  * two subsystems both claiming an ACTIVE CPU AXI Master on one bind target
    -- each subsystem's OWN connectivity self-check passes 2-for-2, and the
    duplicate is visible only to the cross-subsystem layer;
  * two subsystems whose address ranges genuinely overlap;
  * a pair whose ONLY agreeing signal is the VIP class name, which must report
    UNKNOWN/NAME_EVIDENCE_ONLY and must never be promoted;
  * two PASSIVE monitors on one interface (a duplicate, but not a hazard);
  * one physical resource the two environments configure differently;
  * two ACTIVE rows inside ONE subsystem's own matrix claiming one bind target;
  * a subsystem-specific PCIe VIP that must never be promoted, and the raise
    that fires if it ever is.
"""
import json
from pathlib import Path

import pytest

from dv_harness import connectivity as conn
from dv_harness import env_manifest
from dv_harness import inference
from dv_harness import source_authority as sa
from dv_harness import subsystem_command_contract as scc
from dv_harness import subsystem_discovery as sd
from dv_harness import system_resource_inventory as sri

ROOT = Path(__file__).resolve().parents[1]


def _write(path: Path, text: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


# ============================================================================
# Synthetic evidence builders
# ============================================================================

MASTER_ROLE = conn.determine_role_from_port_direction("output")   # vip_role=slave_responder
SLAVE_ROLE = conn.determine_role_from_port_direction("input")     # vip_role=master_initiator


def _matrix_row(*, dut_instance, interface, vip_type, active_passive, bind_target,
                protocol=conn.PROTOCOL_NOT_CLASSIFIED, role=SLAVE_ROLE,
                fabric_side_role=conn.FABRIC_SIDE_ROLE_NOT_CLASSIFIED) -> dict:
    """One connectivity-matrix row in the real `MATRIX_COLUMNS` shape."""
    return {"dut_instance": dut_instance, "interface": interface,
            "direction": "input", "role": role, "vip_type": vip_type, "count": 1,
            "active_passive": active_passive, "bind_target": bind_target,
            "tier": conn.BindTier.T1_ALREADY_DECIDED.value, "protocol": protocol,
            "fabric_side_role": fabric_side_role}


def _write_matrix(path: Path, rows) -> Path:
    return _write(path, json.dumps({"columns": conn.MATRIX_COLUMNS, "rows": list(rows)}))


def _soc_arch_map(path: Path, *, regions, clocks=("core_clk",), resets=("core_rst_n",)) -> Path:
    """`regions` is [(name, base, size, bus)] -- `bus` may be None to model a
    real project whose SoC map has no bus column, which is what makes an
    address domain COARSE rather than RESOLVED."""
    entries = []
    for name, base, size, bus in regions:
        entry = {"name": name, "base_address": base, "size_bytes": size}
        if bus:
            entry["bus"] = bus
        entries.append(entry)
    return _write(path, json.dumps({
        "schema_version": "1.0",
        "address_map": entries,
        "clocks": [{"name": c, "frequency_mhz": 100} for c in clocks],
        "resets": [{"name": r, "active_level": "low", "clock": clocks[0]} for r in resets],
    }))


def _vip_dump(path: Path, instances) -> Path:
    """`instances` is [(instance_path, vip_type, config_fields)]."""
    return _write(path, json.dumps({"schema_version": "1.0", "vip_instances": [
        {"instance_path": p, "vip_type": t, "config_fields": dict(c)}
        for p, t, c in instances]}))


def _subsystem_sources(tmp_path: Path, name: str, *, rows, vip_instances=(),
                       regions=(("CTRL", "0x14000000", 4096, "AXI4"),),
                       clocks=("core_clk",), release_sha="sha-none",
                       **kwargs) -> sri.SubsystemResourceSources:
    """A synthetic subsystem: a real schema-valid env.manifest.json (generated
    by the real generator, not hand-written JSON) plus a connectivity matrix."""
    env = tmp_path / "generated" / name.lower()
    (env / ".dv-harness").mkdir(parents=True, exist_ok=True)
    manifest_path = env / ".dv-harness" / "env.manifest.json"
    env_manifest.generate_and_write(
        manifest_path,
        vip_config_dump_path=(_vip_dump(env / "vip_dump.json", vip_instances)
                              if vip_instances else None),
        soc_arch_map_path=_soc_arch_map(env / "soc_arch_map.json",
                                        regions=regions, clocks=clocks))
    matrix_path = _write_matrix(env / ".dv-harness" / "connectivity_matrix.json", rows)
    return sri.SubsystemResourceSources(
        subsystem_id=name, environment_root=str(env),
        env_manifest_path=str(manifest_path),
        connectivity_matrix_path=str(matrix_path),
        release_sha=release_sha, **kwargs)


# The recurring conflict fixture: TWO subsystems, each with exactly ONE active
# CPU AXI Master VIP, both binding the SAME absolute SoC hierarchy path.
SHARED_CPU_BIND = "chip.soc.cpu_axi_m"


def _two_subsystems_sharing_one_cpu_master(tmp_path: Path, *, b_active=True,
                                           b_config=None, a_config=None):
    a = _subsystem_sources(
        tmp_path, "SUBSYS_A",
        rows=[_matrix_row(dut_instance="chip.soc.cpu_axi_m", interface="axi_m",
                          vip_type="svt_axi_master_agent", active_passive="active",
                          bind_target=SHARED_CPU_BIND, protocol="AXI4",
                          role=MASTER_ROLE,
                          fabric_side_role=conn.FABRIC_SIDE_MASTER_INTERFACE)],
        vip_instances=[(SHARED_CPU_BIND, "svt_axi_master_agent",
                        a_config if a_config is not None else {"data_width": "64"})],
        release_sha="aaa111")
    b = _subsystem_sources(
        tmp_path, "SUBSYS_B",
        rows=[_matrix_row(dut_instance="chip.soc.cpu_axi_m", interface="axi_m",
                          vip_type="svt_axi_master_agent",
                          active_passive="active" if b_active else "passive",
                          bind_target=SHARED_CPU_BIND, protocol="AXI4",
                          role=MASTER_ROLE,
                          fabric_side_role=conn.FABRIC_SIDE_MASTER_INTERFACE)],
        vip_instances=[(SHARED_CPU_BIND, "svt_axi_master_agent",
                        b_config if b_config is not None else {"data_width": "64"})],
        release_sha="bbb222")
    return a, b


# ============================================================================
# Drift guards: the requirement's own field lists, held against the code
# ============================================================================

# Copied verbatim from the master prompt (SYS-9's "Capture ..." sentence).
SYS9_REQUIREMENT_TEXT = (
    "RESOURCE_ID, TYPE, PROTOCOL, ROLE, HIERARCHY, ACTIVE/PASSIVE, CONFIGURATION, "
    "OWNER_SUBSYSTEM, SHAREABLE, EXCLUSIVE, CLOCK, RESET, ADDRESS DOMAIN, "
    "DEPENDENCIES, EVIDENCE, CONFIDENCE")

# Copied verbatim from SYS-10's "Compare ..." sentence.
SYS10_REQUIREMENT_TEXT = (
    "protocol, role, physical interface, hierarchy, clock/reset, address domain, "
    "configuration, driver ownership, active/passive mode, intended function")


def _slug(item: str) -> str:
    return (item.lower().replace("/", "_").replace(" ", "_")
            .replace("active_passive_mode", "active_passive"))


def test_sys9_fields_match_the_requirements_own_list_one_to_one():
    items = SYS9_REQUIREMENT_TEXT.split(", ")
    assert len(items) == len(sri.SYS9_FIELDS) == 16
    for item, field_name in zip(items, sri.SYS9_FIELDS):
        slug = _slug(item)
        assert slug == field_name or slug in field_name or field_name.endswith(slug), (
            item, field_name)


def test_sys10_signals_match_the_requirements_own_list_one_to_one():
    items = SYS10_REQUIREMENT_TEXT.split(", ")
    assert len(items) == len(sri.IDENTITY_SIGNALS) == 10
    for item, signal in zip(items, sri.IDENTITY_SIGNALS):
        assert _slug(item).replace("clock_reset", "clock_reset") == signal, (item, signal)


def test_sys11_classes_are_exactly_the_seven_the_requirement_names():
    assert set(sri.RELATIONSHIP_CLASSES) == {
        "SAME_PHYSICAL_RESOURCE", "SHARED_LOGICAL_RESOURCE", "INDEPENDENT_RESOURCE",
        "MONITOR_ONLY_DUPLICATE", "CONFIGURATION_CONFLICT", "DRIVER_CONFLICT", "UNKNOWN"}


def test_sys13_promotable_types_are_the_requirements_own_list():
    """SYS-13 names exactly: CPU AXI Master, APB Master, AHB Master, SoC
    Register Access, DDR/Memory Model, Interrupt Controller, Clock/Reset,
    Firmware Agent."""
    assert sri.SHARED_SOC_INFRASTRUCTURE_TYPES == frozenset({
        sri.RT_CPU_BUS_MASTER, sri.RT_APB_MASTER, sri.RT_AHB_MASTER, sri.RT_AXI_MASTER,
        sri.RT_REGISTER_ACCESS_AGENT, sri.RT_MEMORY_MODEL, sri.RT_INTERRUPT_AGENT,
        sri.RT_CLOCK_RESET_AGENT, sri.RT_FIRMWARE_AGENT})
    assert sri.RT_SCOREBOARD not in sri.SHARED_SOC_INFRASTRUCTURE_TYPES
    assert sri.RT_VIP_AGENT not in sri.SHARED_SOC_INFRASTRUCTURE_TYPES


def test_confidence_uses_the_one_existing_scorer_not_a_second_vocabulary():
    """SYS-9's CONFIDENCE must be `inference.score_confidence()`'s output.
    `dv_harness_tests/test_confidence_vocabulary_separation.py` exists to stop
    a fourth confidence-ish mechanism appearing; this holds SYS-9 to the same
    rule from the other side."""
    assert sri.inference is inference
    src = (ROOT / "dv_harness" / "system_resource_inventory.py").read_text(encoding="utf-8")
    assert "inference.score_confidence(" in src
    # No parallel level list of its own.
    assert '"HIGH" if' not in src and "CONFIDENCE_LEVELS = " not in src


# ============================================================================
# connectivity.find_active_bind_target_collisions -- SYS-12 WITHIN one matrix
# ============================================================================

def test_two_active_rows_claiming_one_bind_target_in_one_matrix_are_reported():
    """The concrete hole this primitive closes: nothing in connectivity.py
    ever checked bind_target uniqueness, so two ACTIVE rows claiming the same
    bind target passed every existing gate -- including the self-check
    identity, which they still pass here."""
    rows = [
        _matrix_row(dut_instance="chip.a", interface="axi_m", vip_type="svt_axi_master_agent",
                    active_passive="active", bind_target=SHARED_CPU_BIND),
        _matrix_row(dut_instance="chip.b", interface="axi_m2", vip_type="svt_axi_master_agent",
                    active_passive="active", bind_target=SHARED_CPU_BIND),
    ]
    # The pre-existing arithmetic is untouched and still passes -- which is
    # exactly why a separate check was needed.
    assert conn.verify_matrix_self_check_identity(rows)["identity_holds"] is True

    collisions = conn.find_active_bind_target_collisions(rows)
    assert len(collisions) == 1
    assert collisions[0]["bind_target"] == SHARED_CPU_BIND
    assert collisions[0]["active_claim_count"] == 2
    assert collisions[0]["resolution"] == "STOP_AUTOMATIC_INTEGRATION_UNTIL_OWNERSHIP_RESOLVED"
    assert sorted(collisions[0]["rows"]) == ["chip.a::axi_m", "chip.b::axi_m2"]


def test_a_passive_monitor_sharing_an_active_rows_bind_target_is_not_a_collision():
    """Two ACTIVE claims are the hazard. An active driver plus a passive
    monitor on one interface is normal and must not be reported."""
    rows = [
        _matrix_row(dut_instance="chip.a", interface="axi_m", vip_type="svt_axi_master_agent",
                    active_passive="active", bind_target=SHARED_CPU_BIND),
        _matrix_row(dut_instance="chip.b", interface="axi_mon", vip_type="svt_axi_monitor",
                    active_passive="passive", bind_target=SHARED_CPU_BIND),
    ]
    assert conn.find_active_bind_target_collisions(rows) == []


def test_no_vip_and_empty_bind_target_rows_are_ignored_by_the_collision_check():
    rows = [
        _matrix_row(dut_instance="chip.a", interface="i0", vip_type="NONE",
                    active_passive="active", bind_target=SHARED_CPU_BIND),
        _matrix_row(dut_instance="chip.b", interface="i1", vip_type="NONE",
                    active_passive="active", bind_target=SHARED_CPU_BIND),
        _matrix_row(dut_instance="chip.c", interface="i2", vip_type="svt_axi_master_agent",
                    active_passive="active", bind_target=""),
        _matrix_row(dut_instance="chip.d", interface="i3", vip_type="svt_axi_master_agent",
                    active_passive="active", bind_target=""),
    ]
    assert conn.find_active_bind_target_collisions(rows) == []


# ============================================================================
# SYS-9: resource type / shareable / clock / address domain derivations
# ============================================================================

def test_resource_type_from_amba_protocol_and_port_direction_is_structural():
    result = sri.classify_resource_type(
        vip_type="some_unhelpfully_named_thing", hierarchy="chip.u0",
        protocol="AXI4", role=MASTER_ROLE,
        fabric_side_role=conn.FABRIC_SIDE_MASTER_INTERFACE)
    assert result["resource_type"] == sri.RT_AXI_MASTER
    assert result["type_basis"] == "AMBA_PROTOCOL_AND_PORT_DIRECTION"


def test_resource_type_falls_back_to_a_name_token_and_says_so():
    result = sri.classify_resource_type(vip_type="svt_cpu_axi_master_agent",
                                        hierarchy="chip.cpu")
    assert result["resource_type"] == sri.RT_CPU_BUS_MASTER
    assert result["type_basis"] == "NAME_TOKEN_MATCH"
    assert result["matched_token"] == "cpu_axi"
    assert result["matched_field"] == "vip_type"


def test_resource_type_is_unclassified_rather_than_a_plausible_guess():
    result = sri.classify_resource_type(vip_type="widget", hierarchy="chip.thing")
    assert result["resource_type"] == sri.RT_UNCLASSIFIED
    assert result["type_basis"] == "NO_STRUCTURAL_OR_NAME_EVIDENCE"


def test_an_ambiguous_role_does_not_get_forced_into_master_or_slave():
    """AMBIGUOUS_FROM_DIRECTION_ALONE settles nothing, so the structural
    branch must not fire on it."""
    result = sri.classify_resource_type(
        vip_type="widget", hierarchy="chip.u0", protocol="AXI4",
        role=conn.determine_role_from_port_direction("inout"))
    assert result["type_basis"] != "AMBA_PROTOCOL_AND_PORT_DIRECTION"


@pytest.mark.parametrize("active_passive,resource_type,shareable,exclusive", [
    ("active", sri.RT_CPU_BUS_MASTER, sri.SHAREABLE_CONDITIONAL, sri.EXCLUSIVE_YES),
    ("active", sri.RT_VIP_AGENT, sri.SHAREABLE_NO, sri.EXCLUSIVE_YES),
    ("passive", sri.RT_CPU_BUS_MASTER, sri.SHAREABLE_YES, sri.EXCLUSIVE_NO),
    ("", sri.RT_CPU_BUS_MASTER, sri.SHAREABLE_UNKNOWN, sri.EXCLUSIVE_UNKNOWN),
])
def test_shareable_and_exclusive_are_derived_three_valued(active_passive, resource_type,
                                                          shareable, exclusive):
    result = sri.derive_shareable_exclusive(active_passive, resource_type)
    assert result["shareable"] == shareable
    assert result["exclusive"] == exclusive
    assert result["basis"]


def test_clock_reset_from_rtl_port_evidence_uses_connectivitys_own_resolver(tmp_path):
    found = sri.resolve_clock_reset(
        hierarchy="chip.u_axi", interface="S_AXI", protocol="AXI4",
        module_ports={"u_axi": ["S_AXI_ACLK", "S_AXI_ARESETN", "S_AXI_AWADDR"]},
        clock_reset_layer={})
    assert found["clock"] == "S_AXI_ACLK"
    assert found["reset"] == "S_AXI_ARESETN"
    assert "connectivity.find_amba_clock_reset_ports" in found["basis"]


def test_clock_reset_falls_back_to_a_single_clock_domain_but_never_to_two(tmp_path):
    one = sri.resolve_clock_reset(
        hierarchy="chip.u0", interface="i", protocol="AXI4", module_ports={},
        clock_reset_layer={"status": "LOADED",
                           "clocks": [{"name": "core_clk"}],
                           "resets": [{"name": "core_rst_n"}]})
    assert (one["clock"], one["reset"]) == ("core_clk", "core_rst_n")
    assert one["basis"].startswith("SINGLE_CLOCK_DOMAIN_IN_SUBSYSTEM")

    two = sri.resolve_clock_reset(
        hierarchy="chip.u0", interface="i", protocol="AXI4", module_ports={},
        clock_reset_layer={"status": "LOADED",
                           "clocks": [{"name": "core_clk"}, {"name": "phy_clk"}],
                           "resets": [{"name": "core_rst_n"}, {"name": "phy_rst_n"}]})
    assert (two["clock"], two["reset"]) == (sri.UNRESOLVED, sri.UNRESOLVED)


def test_address_domain_is_resolved_coarse_or_unresolved_never_assumed():
    loaded = {"status": "LOADED", "entries": [
        {"name": "CTRL", "base_address": "0x14000000", "size_bytes": 4096, "bus": "AXI4"},
        {"name": "MEM", "base_address": "0x20000000", "size_bytes": 65536, "bus": "APB"},
    ]}
    resolved = sri.resolve_address_domain(hierarchy="chip.u0", protocol="AXI4",
                                          resource_type=sri.RT_AXI_MASTER,
                                          address_map_layer=loaded)
    assert resolved["status"] == "RESOLVED"
    assert [r["name"] for r in resolved["regions"]] == ["CTRL"]

    no_bus = {"status": "LOADED", "entries": [
        {"name": "CTRL", "base_address": "0x14000000", "size_bytes": 4096}]}
    coarse = sri.resolve_address_domain(hierarchy="chip.u0", protocol="AXI4",
                                        resource_type=sri.RT_CPU_BUS_MASTER,
                                        address_map_layer=no_bus)
    assert coarse["status"] == "COARSE"

    absent = sri.resolve_address_domain(hierarchy="chip.u0", protocol="AXI4",
                                        resource_type=sri.RT_AXI_MASTER,
                                        address_map_layer={"status": "NOT_AVAILABLE"})
    assert absent["status"] == sri.UNRESOLVED
    assert absent["regions"] == []


# ============================================================================
# SYS-9: the cross-subsystem inventory itself
# ============================================================================

def test_every_resource_carries_all_sixteen_sys9_fields_and_its_owner(tmp_path):
    a, b = _two_subsystems_sharing_one_cpu_master(tmp_path)
    inventory = sri.build_cross_subsystem_inventory([a, b])
    assert inventory["resource_count"] == 2
    for resource in inventory["resources"]:
        for field_name in sri.SYS9_FIELDS:
            assert field_name in resource, field_name
        assert resource["owner_subsystem"] in ("SUBSYS_A", "SUBSYS_B")
        assert resource["resource_id"].startswith(resource["owner_subsystem"] + "::")
        assert resource["confidence"] in inference.CONFIDENCE_LEVELS


def test_owner_subsystem_makes_two_identical_resources_distinguishable(tmp_path):
    """The load-bearing property: both subsystems' rows are byte-identical in
    every MATRIX_COLUMNS field, and the two records are still distinct."""
    a, b = _two_subsystems_sharing_one_cpu_master(tmp_path)
    inventory = sri.build_cross_subsystem_inventory([a, b])
    ids = [r["resource_id"] for r in inventory["resources"]]
    assert len(set(ids)) == 2
    assert {r["owner_subsystem"] for r in inventory["resources"]} == {"SUBSYS_A", "SUBSYS_B"}
    assert {r["owner_release_sha"] for r in inventory["resources"]} == {"aaa111", "bbb222"}


def test_each_subsystems_own_self_check_passes_while_the_duplicate_stands(tmp_path):
    """The audit's exact scenario, proven: 1 interface / 1 VIP in each
    subsystem means each matrix's identity holds 2-for-2, and the duplicate is
    invisible to every within-one-matrix check."""
    a, b = _two_subsystems_sharing_one_cpu_master(tmp_path)
    inventory = sri.build_cross_subsystem_inventory([a, b])
    for per in inventory["per_subsystem"]:
        assert per["matrix_self_check"]["status"] == "PASS"
        assert per["matrix_self_check"]["verified_interface_count"] == 1
        assert per["matrix_self_check"]["vip_instance_count"] == 1
        assert per["within_subsystem_bind_collisions"] == []

    analysis = sri.build_cross_subsystem_resource_analysis([a, b])
    assert analysis["summary"]["driver_conflicts"] == 1


def test_a_repeated_subsystem_id_is_refused(tmp_path):
    a, _ = _two_subsystems_sharing_one_cpu_master(tmp_path)
    with pytest.raises(sri.SystemResourceInventoryError) as excinfo:
        sri.build_cross_subsystem_inventory([a, a])
    assert excinfo.value.reason == "DUPLICATE_SUBSYSTEM_ID_IN_SOURCES"


def test_a_no_vip_row_is_a_gap_not_a_resource(tmp_path):
    s = _subsystem_sources(
        tmp_path, "SUBSYS_GAP",
        rows=[_matrix_row(dut_instance="chip.a", interface="i0", vip_type="svt_axi_master_agent",
                          active_passive="active", bind_target="chip.a.i0"),
              _matrix_row(dut_instance="chip.b", interface="i1", vip_type="NONE",
                          active_passive="passive", bind_target="chip.b.i1")])
    inventory = sri.build_subsystem_resource_inventory(s)
    assert inventory["resource_count"] == 1
    assert inventory["resources"][0]["hierarchy"] == "chip.a"


def test_an_unreadable_matrix_is_reported_not_silently_empty(tmp_path):
    s = sri.SubsystemResourceSources(subsystem_id="SUBSYS_X",
                                     connectivity_matrix_path=str(tmp_path / "nope.json"))
    inventory = sri.build_subsystem_resource_inventory(s)
    assert inventory["resources"] == []
    assert inventory["connectivity_matrix_status"].startswith("CONNECTIVITY_MATRIX_UNREADABLE")
    assert inventory["matrix_self_check"]["status"] == "NOT_RUN"


def test_a_vip_instance_absent_from_the_matrix_is_still_inventoried(tmp_path):
    """A VIP in the live config dump that the matrix never mentions is exactly
    where a cross-subsystem duplicate hides, so it is inventoried with an
    honest UNKNOWN active/passive rather than dropped."""
    s = _subsystem_sources(
        tmp_path, "SUBSYS_HIDDEN",
        rows=[_matrix_row(dut_instance="chip.a", interface="i0", vip_type="svt_axi_master_agent",
                          active_passive="active", bind_target="chip.a.i0")],
        vip_instances=[("chip.a.i0", "svt_axi_master_agent", {"data_width": "64"}),
                       ("chip.hidden.reg_access", "svt_reg_access_agent", {"width": "32"})])
    inventory = sri.build_subsystem_resource_inventory(s)
    hierarchies = {r["hierarchy"] for r in inventory["resources"]}
    assert hierarchies == {"chip.a", "chip.hidden.reg_access"}
    hidden = next(r for r in inventory["resources"] if r["hierarchy"].endswith("reg_access"))
    assert hidden["shareable"] == sri.SHAREABLE_UNKNOWN
    assert hidden["active_passive"] == ""


# ============================================================================
# SYS-10 / SYS-11: comparison and classification
# ============================================================================

def _analyze(sources):
    return sri.build_cross_subsystem_resource_analysis(sources)


def test_two_subsystems_actively_driving_one_bind_target_are_a_driver_conflict(tmp_path):
    a, b = _two_subsystems_sharing_one_cpu_master(tmp_path)
    analysis = _analyze([a, b])
    assert len(analysis["relationships"]) == 1
    rel = analysis["relationships"][0]
    assert rel["relationship"] == sri.REL_DRIVER_CONFLICT
    assert "physical_interface" in rel["physical_identity_evidence"]
    assert rel["both_active"] is True
    signals = rel["comparison"]["signals"]
    assert signals["physical_interface"]["verdict"] == sri.AGREE
    assert signals["active_passive"]["verdict"] == sri.AGREE


def test_one_active_one_passive_on_one_interface_is_same_physical_not_a_conflict(tmp_path):
    a, b = _two_subsystems_sharing_one_cpu_master(tmp_path, b_active=False)
    analysis = _analyze([a, b])
    rel = analysis["relationships"][0]
    assert rel["relationship"] == sri.REL_SAME_PHYSICAL
    assert analysis["summary"]["driver_conflicts"] == 0


def test_two_passive_monitors_on_one_interface_are_a_monitor_only_duplicate(tmp_path):
    a = _subsystem_sources(
        tmp_path, "SUBSYS_A",
        rows=[_matrix_row(dut_instance="chip.soc.cpu_axi_m", interface="axi_m",
                          vip_type="svt_axi_monitor", active_passive="passive",
                          bind_target=SHARED_CPU_BIND, protocol="AXI4", role=MASTER_ROLE)])
    b = _subsystem_sources(
        tmp_path, "SUBSYS_B",
        rows=[_matrix_row(dut_instance="chip.soc.cpu_axi_m", interface="axi_m",
                          vip_type="svt_axi_monitor", active_passive="passive",
                          bind_target=SHARED_CPU_BIND, protocol="AXI4", role=MASTER_ROLE)])
    analysis = _analyze([a, b])
    assert analysis["relationships"][0]["relationship"] == sri.REL_MONITOR_ONLY_DUPLICATE
    assert analysis["active_driver_conflict_rule"]["automatic_integration_allowed"] is True


def test_one_physical_resource_configured_differently_is_a_configuration_conflict(tmp_path):
    a, b = _two_subsystems_sharing_one_cpu_master(
        tmp_path, b_active=False,
        a_config={"data_width": "64", "id_width": "4"},
        b_config={"data_width": "32", "id_width": "4"})
    analysis = _analyze([a, b])
    rel = analysis["relationships"][0]
    assert rel["relationship"] == sri.REL_CONFIGURATION_CONFLICT
    differing = rel["comparison"]["signals"]["configuration"]["differing"]
    assert [d["field"] for d in differing] == ["data_width"]


def test_a_driver_conflict_outranks_a_simultaneous_configuration_disagreement(tmp_path):
    """Both are true; SYS-12's stop rule is triggered by the two drivers, so
    DRIVER_CONFLICT is the verdict and the configuration finding is carried
    rather than lost."""
    a, b = _two_subsystems_sharing_one_cpu_master(
        tmp_path, b_active=True,
        a_config={"data_width": "64"}, b_config={"data_width": "32"})
    rel = _analyze([a, b])["relationships"][0]
    assert rel["relationship"] == sri.REL_DRIVER_CONFLICT
    assert rel["configuration_disagrees"] is True
    assert "data_width" in rel["reason"]


def test_matching_class_names_alone_never_decide_a_duplicate(tmp_path):
    """SYS-10's own sentence, as a test. Two `svt_axi_master_agent`s in two
    subsystems with UNRELATED hierarchies, DIFFERENT bind targets, no shared
    config field and disjoint address domains agree on exactly one signal --
    intended_function, which is name-derived. The verdict must be UNKNOWN."""
    a = _subsystem_sources(
        tmp_path, "SUBSYS_A",
        rows=[_matrix_row(dut_instance="pcie.core.axi_m", interface="axi_m",
                          vip_type="svt_axi_master_agent", active_passive="active",
                          bind_target="pcie.core.axi_m", role=MASTER_ROLE)],
        regions=(("PCIE_CTRL", "0x14000000", 4096, "AXI4"),))
    b = _subsystem_sources(
        tmp_path, "SUBSYS_B",
        rows=[_matrix_row(dut_instance="usb.core.axi_m", interface="axi_m",
                          vip_type="svt_axi_master_agent", active_passive="active",
                          bind_target="usb.core.axi_m", role=MASTER_ROLE)],
        regions=(("USB_CTRL", "0x30000000", 4096, "AXI4"),))
    analysis = _analyze([a, b])
    rel = analysis["relationships"][0]
    assert rel["comparison"]["signals"]["intended_function"]["verdict"] == sri.AGREE
    assert rel["comparison"]["identity_agreeing_signals"] == []
    assert rel["relationship"] == sri.REL_UNKNOWN
    assert rel["name_evidence_only"] is True
    assert "NAME_EVIDENCE_ONLY" in rel["reason"]
    # And it is HELD, never auto-integrated: both sides are active.
    rule = analysis["active_driver_conflict_rule"]
    assert rule["automatic_integration_allowed"] is False
    assert rule["decisions"][0]["integration_status"] == sri.INTEGRATION_HELD


def test_overlapping_address_ranges_across_two_subsystems_agree_on_that_signal(tmp_path):
    """Two independently-declared SoC maps whose AXI4 regions genuinely
    overlap. With protocol + role + address domain agreeing (two logical
    signals) and no physical-identity evidence, this is a SHARED_LOGICAL
    resource -- explicitly NOT a proven physical duplicate."""
    a = _subsystem_sources(
        tmp_path, "SUBSYS_A",
        rows=[_matrix_row(dut_instance="a.core.reg_access", interface="apb_m",
                          vip_type="svt_reg_access_agent", active_passive="passive",
                          bind_target="a.core.reg_access", protocol="AXI4",
                          role=MASTER_ROLE)],
        regions=(("SHARED_WINDOW", "0x40000000", 0x10000, "AXI4"),))
    b = _subsystem_sources(
        tmp_path, "SUBSYS_B",
        rows=[_matrix_row(dut_instance="b.core.reg_access", interface="apb_m",
                          vip_type="svt_reg_access_agent", active_passive="passive",
                          bind_target="b.core.reg_access", protocol="AXI4",
                          role=MASTER_ROLE)],
        regions=(("SHARED_WINDOW_ALIAS", "0x40008000", 0x10000, "AXI4"),))
    rel = _analyze([a, b])["relationships"][0]
    address = rel["comparison"]["signals"]["address_domain"]
    assert address["verdict"] == sri.AGREE
    assert address["overlaps"][0]["overlap_start"] == 0x40008000
    assert address["overlaps"][0]["overlap_end"] == 0x40010000
    assert rel["relationship"] == sri.REL_SHARED_LOGICAL
    assert rel["physical_identity_evidence"] == []


def test_disjoint_address_ranges_disagree_rather_than_report_unknown(tmp_path):
    a = _subsystem_sources(
        tmp_path, "SUBSYS_A",
        rows=[_matrix_row(dut_instance="a.core.m", interface="axi_m",
                          vip_type="svt_axi_master_agent", active_passive="passive",
                          bind_target="a.core.m", protocol="AXI4", role=MASTER_ROLE)],
        regions=(("A_WINDOW", "0x40000000", 0x1000, "AXI4"),))
    b = _subsystem_sources(
        tmp_path, "SUBSYS_B",
        rows=[_matrix_row(dut_instance="b.core.m", interface="axi_m",
                          vip_type="svt_axi_master_agent", active_passive="passive",
                          bind_target="b.core.m", protocol="AXI4", role=MASTER_ROLE)],
        regions=(("B_WINDOW", "0x50000000", 0x1000, "AXI4"),))
    rel = _analyze([a, b])["relationships"][0]
    assert rel["comparison"]["signals"]["address_domain"]["verdict"] == sri.DISAGREE
    assert rel["relationship"] in (sri.REL_UNKNOWN, sri.REL_INDEPENDENT)


def test_a_coarse_address_domain_is_never_compared_as_agreement(tmp_path):
    """Two subsystem-wide maps overlapping says nothing about whether one
    master reaches the other's regions; treating that as agreement would make
    every pair of bus resources look like a duplicate."""
    a = _subsystem_sources(
        tmp_path, "SUBSYS_A",
        rows=[_matrix_row(dut_instance="a.cpu", interface="axi_m",
                          vip_type="svt_cpu_axi_master_agent", active_passive="passive",
                          bind_target="a.cpu", role=MASTER_ROLE)],
        regions=(("W", "0x40000000", 0x10000, None),))
    b = _subsystem_sources(
        tmp_path, "SUBSYS_B",
        rows=[_matrix_row(dut_instance="b.cpu", interface="axi_m",
                          vip_type="svt_cpu_axi_master_agent", active_passive="passive",
                          bind_target="b.cpu", role=MASTER_ROLE)],
        regions=(("W", "0x40000000", 0x10000, None),))
    inventory = sri.build_cross_subsystem_inventory([a, b])
    assert all(r["address_domain"]["status"] == "COARSE" for r in inventory["resources"])
    rel = _analyze([a, b])["relationships"][0]
    assert rel["comparison"]["signals"]["address_domain"]["verdict"] == sri.SIGNAL_UNKNOWN


def test_different_protocols_and_unrelated_hierarchies_are_independent(tmp_path):
    a = _subsystem_sources(
        tmp_path, "SUBSYS_A",
        rows=[_matrix_row(dut_instance="a.core.apb", interface="apb_m",
                          vip_type="svt_apb_master_agent", active_passive="active",
                          bind_target="a.core.apb", protocol="APB4", role=MASTER_ROLE)],
        regions=(("A_W", "0x10000000", 0x1000, "APB4"),))
    b = _subsystem_sources(
        tmp_path, "SUBSYS_B",
        rows=[_matrix_row(dut_instance="b.core.ahb", interface="ahb_m",
                          vip_type="svt_ahb_master_agent", active_passive="active",
                          bind_target="b.core.ahb", protocol="AHB", role=MASTER_ROLE)],
        regions=(("B_W", "0x20000000", 0x1000, "AHB"),))
    analysis = _analyze([a, b])
    rel = analysis["relationships"][0]
    assert rel["comparison"]["signals"]["protocol"]["verdict"] == sri.DISAGREE
    assert rel["relationship"] == sri.REL_INDEPENDENT


def test_a_declared_physical_interface_map_establishes_identity_without_a_shared_bind(tmp_path):
    """Two environments that do NOT share a bind target can still be stated by
    a human to be one SoC pin -- and only a human, never this module."""
    a = _subsystem_sources(
        tmp_path, "SUBSYS_A",
        rows=[_matrix_row(dut_instance="a.core.cpu_m", interface="axi_m",
                          vip_type="svt_cpu_axi_master_agent", active_passive="active",
                          bind_target="a.core.cpu_m", protocol="AXI4", role=MASTER_ROLE)],
        declared_physical_interfaces={"a.core.cpu_m::axi_m": "SOC_CPU_AXI_M"})
    b = _subsystem_sources(
        tmp_path, "SUBSYS_B",
        rows=[_matrix_row(dut_instance="b.core.cpu_m", interface="axi_m",
                          vip_type="svt_cpu_axi_master_agent", active_passive="passive",
                          bind_target="b.core.cpu_m", protocol="AXI4", role=MASTER_ROLE)],
        declared_physical_interfaces={"b.core.cpu_m::axi_m": "SOC_CPU_AXI_M"})
    rel = _analyze([a, b])["relationships"][0]
    assert rel["comparison"]["signals"]["physical_interface"]["basis"] == \
        "DECLARED_PHYSICAL_INTERFACE_MAP"
    assert rel["relationship"] == sri.REL_SAME_PHYSICAL


def test_every_pair_gets_a_verdict_for_all_ten_signals(tmp_path):
    a, b = _two_subsystems_sharing_one_cpu_master(tmp_path)
    comparison = _analyze([a, b])["duplicate_candidates"][0]
    assert list(comparison["signals"]) == list(sri.IDENTITY_SIGNALS)
    assert all(s["verdict"] in (sri.AGREE, sri.DISAGREE, sri.SIGNAL_UNKNOWN)
               for s in comparison["signals"].values())
    assert all(s["basis"] for s in comparison["signals"].values())


def test_pairs_inside_one_subsystem_are_not_cross_subsystem_candidates(tmp_path):
    s = _subsystem_sources(
        tmp_path, "SUBSYS_SOLO",
        rows=[_matrix_row(dut_instance="chip.a", interface="i0",
                          vip_type="svt_axi_master_agent", active_passive="active",
                          bind_target="chip.shared", protocol="AXI4", role=MASTER_ROLE),
              _matrix_row(dut_instance="chip.b", interface="i1",
                          vip_type="svt_axi_master_agent", active_passive="active",
                          bind_target="chip.shared", protocol="AXI4", role=MASTER_ROLE)])
    analysis = _analyze([s])
    assert analysis["duplicate_candidates"] == []
    # It is still caught -- by the WITHIN-subsystem half of SYS-12's rule.
    rule = analysis["active_driver_conflict_rule"]
    assert rule["automatic_integration_allowed"] is False
    within = [d for d in rule["decisions"] if d["scope"] == "WITHIN_SUBSYSTEM"]
    assert len(within) == 1
    assert within[0]["bind_target"] == "chip.shared"
    assert within[0]["integration_status"] == sri.INTEGRATION_STOPPED


# ============================================================================
# SYS-10 driver-ownership signal from the SYS-8 contract set
# ============================================================================

CPU_SIDE_COMMANDS = """\
initial
begin
  `CPUWRITE4B(32'h1400_0000, 32'h1);
  `SMEMMODEL.FILLMEM("/synthetic/trb.hex", 4, 40'h2000_1000, 'd32);
end
"""

SECOND_CPU_SIDE_COMMANDS = """\
initial
begin
  `CPUWRITE4B(32'h1400_0000, 32'h7);
  `SMEMMODEL.FILLMEM("/synthetic/other.hex", 4, 40'h2000_2000, 'd16);
end
"""


def test_driver_ownership_comes_from_the_real_sys8_contract_set(tmp_path):
    """The command-behaviour evidence axis: two subsystems whose command.txt
    both WRITE the same SYS-8 `MODEL:SMEMMODEL` resource. Detected from what
    the commands DO, independently of how either environment is wired."""
    a_cmd = _write(tmp_path / "a" / "command.txt", CPU_SIDE_COMMANDS)
    b_cmd = _write(tmp_path / "b" / "command.txt", SECOND_CPU_SIDE_COMMANDS)
    contract_set = scc.build_contract_set({"SUBSYS_A": [a_cmd], "SUBSYS_B": [b_cmd]})
    written = {r["resource_id"] for c in contract_set["contracts"]
               for r in c["required_resources"] if r["access"] == "WRITE"}
    assert "MEMORY_MODEL:SMEMMODEL" in written

    a = _subsystem_sources(
        tmp_path, "SUBSYS_A",
        rows=[_matrix_row(dut_instance="a.top.SMEMMODEL", interface="mem",
                          vip_type="synth_memory_model", active_passive="passive",
                          bind_target="a.top.SMEMMODEL")])
    b = _subsystem_sources(
        tmp_path, "SUBSYS_B",
        rows=[_matrix_row(dut_instance="b.top.SMEMMODEL", interface="mem",
                          vip_type="synth_memory_model", active_passive="passive",
                          bind_target="b.top.SMEMMODEL")])
    analysis = sri.build_cross_subsystem_resource_analysis(
        [a, b], contract_set=contract_set)
    rel = analysis["relationships"][0]
    ownership = rel["comparison"]["signals"]["driver_ownership"]
    assert ownership["verdict"] == sri.AGREE
    assert "MEMORY_MODEL:SMEMMODEL" in ownership["common_written_resource_ids"]
    assert "driver_ownership" in rel["physical_identity_evidence"]


def test_driver_ownership_is_unknown_without_a_contract_set(tmp_path):
    a, b = _two_subsystems_sharing_one_cpu_master(tmp_path)
    rel = _analyze([a, b])["relationships"][0]
    assert rel["comparison"]["signals"]["driver_ownership"]["verdict"] == sri.SIGNAL_UNKNOWN


# ============================================================================
# SYS-12: the active driver conflict rule
# ============================================================================

def test_a_driver_conflict_stops_automatic_integration_of_that_resource(tmp_path):
    a, b = _two_subsystems_sharing_one_cpu_master(tmp_path)
    rule = _analyze([a, b])["active_driver_conflict_rule"]
    assert rule["automatic_integration_allowed"] is False
    assert len(rule["stopped_resource_ids"]) == 2
    decision = rule["decisions"][0]
    assert decision["integration_status"] == sri.INTEGRATION_STOPPED
    assert decision["scope"] == "CROSS_SUBSYSTEM"
    assert sorted(decision["subsystems"]) == ["SUBSYS_A", "SUBSYS_B"]
    # The preferred model is carried as text a human reads, never built.
    assert "System Virtual Sequencer" in decision["preferred_model"]
    assert "SYS-40" in decision["preferred_model"]


def test_a_clean_pair_leaves_automatic_integration_allowed(tmp_path):
    a, b = _two_subsystems_sharing_one_cpu_master(tmp_path, b_active=False)
    rule = _analyze([a, b])["active_driver_conflict_rule"]
    assert rule["automatic_integration_allowed"] is True
    assert rule["decisions"] == []


def test_configuration_conflicts_escalate_through_the_existing_source_authority(tmp_path):
    """Not a second conflict resolver: two live vip_config dumps are two
    tier-1 claims, and the 9-level order's own answer is that it cannot break
    a tie inside one level."""
    a, b = _two_subsystems_sharing_one_cpu_master(
        tmp_path, b_active=False,
        a_config={"data_width": "64"}, b_config={"data_width": "32"})
    escalations = _analyze([a, b])["configuration_conflict_escalations"]
    assert len(escalations) == 1
    assert escalations[0]["field"] == "data_width"
    assert escalations[0]["conflict"]["verdict"] == sa.VERDICT_UNDECIDABLE
    assert escalations[0]["conflict"]["winner"] is None
    assert len(escalations[0]["conflict"]["tied"]) == 2


# ============================================================================
# SYS-13 / SYS-14: promotion evaluation and ownership preservation
# ============================================================================

def test_a_proven_shared_cpu_master_is_recommended_for_promotion(tmp_path):
    a, b = _two_subsystems_sharing_one_cpu_master(tmp_path, b_active=False)
    analysis = _analyze([a, b])
    promotion = analysis["promotion_evaluation"][0]
    assert promotion["decision"] == sri.PROMOTE_TO_SYSTEM_SHARED
    assert promotion["recommendation_only"] is True
    assert "SYS-40" in promotion["implementation_phase"]
    ownership = analysis["ownership_preservation"]
    assert len(ownership["promotion_candidates"]) == 2
    assert ownership["refactoring_proposed_anywhere"] is False


def test_a_driver_conflict_blocks_promotion_rather_than_promoting(tmp_path):
    a, b = _two_subsystems_sharing_one_cpu_master(tmp_path)
    promotion = _analyze([a, b])["promotion_evaluation"][0]
    assert promotion["decision"] == sri.BLOCKED_PENDING_OWNERSHIP
    assert "SYS-12" in promotion["reason"]


def test_name_only_evidence_blocks_promotion_with_the_requirements_own_reason(tmp_path):
    a = _subsystem_sources(
        tmp_path, "SUBSYS_A",
        rows=[_matrix_row(dut_instance="a.core.cpu_m", interface="i", role=MASTER_ROLE,
                          vip_type="svt_cpu_axi_master_agent", active_passive="passive",
                          bind_target="a.core.cpu_m")],
        regions=(("A_W", "0x10000000", 0x1000, "AXI4"),))
    b = _subsystem_sources(
        tmp_path, "SUBSYS_B",
        rows=[_matrix_row(dut_instance="b.core.cpu_m", interface="i", role=MASTER_ROLE,
                          vip_type="svt_cpu_axi_master_agent", active_passive="passive",
                          bind_target="b.core.cpu_m")],
        regions=(("B_W", "0x20000000", 0x1000, "AXI4"),))
    analysis = _analyze([a, b])
    rel = analysis["relationships"][0]
    assert rel["name_evidence_only"] is True
    promotion = analysis["promotion_evaluation"][0]
    assert promotion["decision"] == sri.BLOCKED_PENDING_EQUIVALENCE
    assert "matching names are insufficient" in promotion["reason"]


def test_a_subsystem_specific_pcie_vip_is_never_promoted(tmp_path):
    """SYS-14. Both sides bind the same target and are passive -- physically
    equivalent by every signal -- and it still must not be promoted, because a
    PCIe VIP is not shared SoC infrastructure."""
    shared = "chip.pcie.link_mon"
    a = _subsystem_sources(
        tmp_path, "PCIE_A",
        rows=[_matrix_row(dut_instance=shared, interface="pipe",
                          vip_type="svt_pcie_device_agent", active_passive="passive",
                          bind_target=shared)])
    b = _subsystem_sources(
        tmp_path, "PCIE_B",
        rows=[_matrix_row(dut_instance=shared, interface="pipe",
                          vip_type="svt_pcie_device_agent", active_passive="passive",
                          bind_target=shared)])
    analysis = _analyze([a, b])
    promotion = analysis["promotion_evaluation"][0]
    assert promotion["decision"] == sri.NOT_ELIGIBLE_SUBSYSTEM_SPECIFIC
    assert "SYS-14" in promotion["reason"]
    ownership = analysis["ownership_preservation"]
    assert ownership["promotion_candidates"] == []
    assert all(d["ownership"] == sri.OWNERSHIP_KEEP_IN_SUBSYSTEM
               for d in ownership["decisions"])


def test_a_scoreboard_duplicate_is_not_eligible_shared_soc_infrastructure(tmp_path):
    shared = "chip.env.sb"
    a = _subsystem_sources(tmp_path, "SUBSYS_A", rows=[
        _matrix_row(dut_instance=shared, interface="sb", vip_type="synth_scoreboard",
                    active_passive="passive", bind_target=shared)])
    b = _subsystem_sources(tmp_path, "SUBSYS_B", rows=[
        _matrix_row(dut_instance=shared, interface="sb", vip_type="synth_scoreboard",
                    active_passive="passive", bind_target=shared)])
    promotion = _analyze([a, b])["promotion_evaluation"][0]
    assert promotion["decision"] == sri.NOT_ELIGIBLE_NOT_SOC_INFRASTRUCTURE
    assert sri.RT_SCOREBOARD in promotion["resource_types"]


def test_ownership_preservation_raises_if_a_subsystem_specific_vip_is_ever_promoted(tmp_path):
    """SYS-14 as an enforced rule rather than a described one: a hand-built
    promotion list that violates it must raise, not warn."""
    shared = "chip.pcie.link_mon"
    a = _subsystem_sources(tmp_path, "PCIE_A", rows=[
        _matrix_row(dut_instance=shared, interface="pipe", vip_type="svt_pcie_device_agent",
                    active_passive="passive", bind_target=shared)])
    b = _subsystem_sources(tmp_path, "PCIE_B", rows=[
        _matrix_row(dut_instance=shared, interface="pipe", vip_type="svt_pcie_device_agent",
                    active_passive="passive", bind_target=shared)])
    inventory = sri.build_cross_subsystem_inventory([a, b])
    ids = [r["resource_id"] for r in inventory["resources"]]
    forged = [{"decision": sri.PROMOTE_TO_SYSTEM_SHARED,
               "resource_a": ids[0], "resource_b": ids[1]}]
    with pytest.raises(sri.SystemResourceInventoryError) as excinfo:
        sri.apply_ownership_preservation(inventory, forged)
    assert excinfo.value.reason == "SYS14_SUBSYSTEM_SPECIFIC_VIP_PROMOTED"


def test_every_resource_gets_an_ownership_decision_with_a_reason(tmp_path):
    a, b = _two_subsystems_sharing_one_cpu_master(tmp_path)
    ownership = _analyze([a, b])["ownership_preservation"]
    assert len(ownership["decisions"]) == 2
    for decision in ownership["decisions"]:
        assert decision["ownership"] in (sri.OWNERSHIP_KEEP_IN_SUBSYSTEM,
                                         sri.OWNERSHIP_PROMOTION_CANDIDATE)
        assert decision["reason"]
        assert decision["refactoring_proposed"] is False


# ============================================================================
# Reporting
# ============================================================================

def test_the_report_carries_every_sys9_to_sys14_section(tmp_path):
    a, b = _two_subsystems_sharing_one_cpu_master(tmp_path)
    report = sri.format_resource_report(_analyze([a, b]))
    for heading in ("SYS-9 RESOURCE INVENTORY",
                    "SYS-10 / SYS-11 RESOURCE RELATIONSHIPS",
                    "SYS-12 ACTIVE DRIVER CONFLICT RULE",
                    "SYS-13 SHARED VIP PROMOTION EVALUATION",
                    "SYS-14 SUBSYSTEM OWNERSHIP PRESERVATION",
                    "PHASE BOUNDARY"):
        assert heading in report
    assert "OWNER_SUBSYSTEM" in report
    assert "DRIVER_CONFLICT" in report
    assert "SYSTEM-LEVEL IMPLEMENTATION NOT STARTED" in report


def test_an_empty_relationship_set_says_so_rather_than_implying_cleanliness(tmp_path):
    s = _subsystem_sources(tmp_path, "SUBSYS_SOLO", rows=[
        _matrix_row(dut_instance="chip.a", interface="i", vip_type="svt_axi_master_agent",
                    active_passive="active", bind_target="chip.a")])
    report = sri.format_resource_report(_analyze([s]))
    assert "not a proof that no duplicate exists" in report


# ============================================================================
# SYS-39/SYS-40 scope boundary -- asserted, not trusted
# ============================================================================

def _tree_snapshot(root: Path) -> dict:
    return {str(p.relative_to(root)): p.read_bytes()
            for p in sorted(root.rglob("*")) if p.is_file()}


def test_a_full_run_writes_nothing_anywhere(tmp_path):
    a, b = _two_subsystems_sharing_one_cpu_master(tmp_path)
    before = _tree_snapshot(tmp_path)
    analysis = _analyze([a, b])
    sri.format_resource_report(analysis)
    assert _tree_snapshot(tmp_path) == before
    assert analysis["artifacts_modified"] is False
    assert analysis["inventory"]["artifacts_modified"] is False


def test_the_report_contains_no_uvm_source_or_command_txt_content(tmp_path):
    a, b = _two_subsystems_sharing_one_cpu_master(tmp_path)
    report = sri.format_resource_report(_analyze([a, b]))
    # Line-anchored where the bare word also occurs in English prose ("in this
    # module creates a shared agent..."), so the check tests for real
    # SystemVerilog rather than for the letters that spell it.
    for forbidden in ("\nclass ", "endclass", "`uvm_component_utils", "\nmodule ",
                      "endmodule", "uvm_sequence", "virtual task", "type_id::create",
                      "`CPUWRITE", "`HOSTWRITE"):
        assert forbidden not in report, forbidden


def test_the_soc_composers_cross_subsystem_stubs_still_raise(tmp_path):
    """SYS-26/27/30 content stays out of this effort entirely. Filling these
    in is SYS-40 and needs its own explicit human approval."""
    from dv_harness.uvm_generator import soc_environment_composer as sec
    manifest = {"subsystems": [{"name": "SUBSYS_A"}, {"name": "SUBSYS_B"}]}
    for fn in (sec.cross_subsystem_scenarios, sec.end_to_end_scoreboard,
               sec.system_coverage):
        with pytest.raises(NotImplementedError):
            fn(manifest)


# ============================================================================
# End-to-end through the real front door
# ============================================================================

def _registered_env(tmp_path: Path, name: str, *, rows, vip_instances, command_text,
                    regions, release_sha) -> Path:
    """A synthetic subsystem environment complete enough for SYS-1 to classify
    it EXISTS_READY, carrying its own connectivity matrix and command.txt."""
    from dv_harness.uvm_generator import run_profile

    env = tmp_path / "generated" / name.lower()
    (env / ".dv-harness").mkdir(parents=True, exist_ok=True)
    _write(env / "command.txt", command_text)
    for rel in ("rtl/dut_core.sv", "env/synth_env.sv", "env/synth_agent.sv",
                "env/synth_scoreboard.sv", "vip/svt_synth_vip.sv", "Makefile",
                "filelist.f", "test/synth_test.sv", "seq/synth_seq.sv",
                "tb/tb_top.sv", "cfg/synth_config.sv", "cfg/clock_reset_map.json",
                "logs/sim.log", "regression.list", "docs/readme.md"):
        _write(env / rel, "// synthetic fixture, empty on purpose\n")
    env_manifest.generate_and_write(
        env / ".dv-harness" / "env.manifest.json",
        vip_config_dump_path=_vip_dump(env / "vip_dump.json", vip_instances),
        soc_arch_map_path=_soc_arch_map(env / "soc_arch_map.json", regions=regions))
    _write_matrix(env / ".dv-harness" / "connectivity_matrix.json", rows)
    profile = run_profile.new_empty_profile("makefile", str(env / "Makefile"), "SYNTH", "synth_")
    profile["runtime_params"] = [{"name": "WAVE", "type": "bool01", "default": "0"}]
    profile["targets"] = [{"name": "compile"}, {"name": "sim"}]
    _write(env / ".dv-harness" / "run_profile.json", json.dumps(profile))
    return env


def test_full_flow_from_selection_through_sys14(tmp_path):
    rows_a = [_matrix_row(dut_instance="chip.soc.cpu_axi_m", interface="axi_m",
                          vip_type="svt_cpu_axi_master_agent", active_passive="active",
                          bind_target=SHARED_CPU_BIND, protocol="AXI4", role=MASTER_ROLE)]
    rows_b = [_matrix_row(dut_instance="chip.soc.cpu_axi_m", interface="axi_m",
                          vip_type="svt_cpu_axi_master_agent", active_passive="active",
                          bind_target=SHARED_CPU_BIND, protocol="AXI4", role=MASTER_ROLE)]
    a = _registered_env(tmp_path, "SUBSYS_A", rows=rows_a,
                        vip_instances=[(SHARED_CPU_BIND, "svt_cpu_axi_master_agent",
                                        {"data_width": "64"})],
                        command_text=CPU_SIDE_COMMANDS,
                        regions=(("CTRL", "0x14000000", 4096, "AXI4"),),
                        release_sha="aaa111")
    b = _registered_env(tmp_path, "SUBSYS_B", rows=rows_b,
                        vip_instances=[(SHARED_CPU_BIND, "svt_cpu_axi_master_agent",
                                        {"data_width": "64"})],
                        command_text=SECOND_CPU_SIDE_COMMANDS,
                        regions=(("CTRL", "0x14000000", 4096, "AXI4"),),
                        release_sha="bbb222")

    registry = tmp_path / ".dv-harness" / "soc-composer" / "subsystem_environment_registry.json"
    _write(registry, json.dumps({"subsystems": [
        {"name": "SUBSYS_A",
         "environment_manifest": str(a / ".dv-harness" / "env.manifest.json"),
         "release_sha": "aaa111", "qualification_state": "REGRESSION_QUALIFIED",
         "interface_compatibility": "PASS", "clock_reset_compatibility": "PASS"},
        {"name": "SUBSYS_B",
         "environment_manifest": str(b / ".dv-harness" / "env.manifest.json"),
         "release_sha": "bbb222", "qualification_state": "REGRESSION_QUALIFIED",
         "interface_compatibility": "PASS", "clock_reset_compatibility": "PASS"},
    ]}))
    _write(sd.candidate_sources_path(tmp_path), json.dumps({"candidates": [
        {"name": "SUBSYS_A", "protocol": "SYNTH_A", "environment_path": str(a),
         "version_sha": "aaa111"},
        {"name": "SUBSYS_B", "protocol": "SYNTH_B", "environment_path": str(b),
         "version_sha": "bbb222"},
    ]}))

    result = sri.analyze_selected_subsystem_resources(
        tmp_path, ["SUBSYS_A", "SUBSYS_B"])
    assert result["selection"]["selection_admissible"] is True
    analysis = result["resource_analysis"]
    assert analysis["summary"]["subsystems"] == ["SUBSYS_A", "SUBSYS_B"]
    assert analysis["summary"]["resource_count"] == 2
    assert analysis["summary"]["driver_conflicts"] == 1
    assert analysis["active_driver_conflict_rule"]["automatic_integration_allowed"] is False
    # The SYS-8 contract set really reached the driver-ownership signal.
    rel = analysis["relationships"][0]
    assert rel["comparison"]["signals"]["driver_ownership"]["verdict"] in (
        sri.AGREE, sri.SIGNAL_UNKNOWN)
    # OWNER_SUBSYSTEM's release_sha came from the SYS-1 discovery row.
    assert {r["owner_release_sha"] for r in analysis["inventory"]["resources"]} == {
        "aaa111", "bbb222"}


def test_the_front_door_does_not_bypass_sys1s_explicit_selection_refusal(tmp_path):
    result = sri.analyze_selected_subsystem_resources(tmp_path, [])
    assert result["selection"]["selection_admissible"] is False
    assert result["selection"]["refusal_reason"] == "NO_EXPLICIT_SELECTION"
    assert result["resource_analysis"]["summary"]["resource_count"] == 0


def test_the_cli_verb_exits_2_while_sys12_has_stopped_a_resource(tmp_path):
    """The real front door, driven as a subprocess: a standing driver conflict
    must not read as a clean run to a CI step."""
    import subprocess
    import sys

    rows = [_matrix_row(dut_instance="chip.soc.cpu_axi_m", interface="axi_m",
                        vip_type="svt_cpu_axi_master_agent", active_passive="active",
                        bind_target=SHARED_CPU_BIND, protocol="AXI4", role=MASTER_ROLE)]
    for name, sha in (("SUBSYS_A", "aaa111"), ("SUBSYS_B", "bbb222")):
        _registered_env(tmp_path, name, rows=rows,
                        vip_instances=[(SHARED_CPU_BIND, "svt_cpu_axi_master_agent",
                                        {"data_width": "64"})],
                        command_text=CPU_SIDE_COMMANDS,
                        regions=(("CTRL", "0x14000000", 4096, "AXI4"),),
                        release_sha=sha)
    _write(sd.candidate_sources_path(tmp_path), json.dumps({"candidates": [
        {"name": n, "protocol": "SYNTH", "environment_path": str(tmp_path / "generated" / n.lower())}
        for n in ("SUBSYS_A", "SUBSYS_B")]}))
    _write(tmp_path / ".dv-harness" / "soc-composer" / "subsystem_environment_registry.json",
           json.dumps({"subsystems": [
               {"name": n,
                "environment_manifest": str(tmp_path / "generated" / n.lower()
                                            / ".dv-harness" / "env.manifest.json"),
                "release_sha": sha, "qualification_state": "REGRESSION_QUALIFIED",
                "interface_compatibility": "PASS", "clock_reset_compatibility": "PASS"}
               for n, sha in (("SUBSYS_A", "aaa111"), ("SUBSYS_B", "bbb222"))]}))

    proc = subprocess.run(
        [sys.executable, "-m", "dv_harness.cli", "--project-root", str(tmp_path),
         "system-resource-inventory", "--select", "SUBSYS_A", "--select", "SUBSYS_B"],
        cwd=str(ROOT), capture_output=True, text=True)
    assert proc.returncode == 2, proc.stderr[-2000:]
    assert "SYS-12 ACTIVE DRIVER CONFLICT RULE" in proc.stdout
    assert "STOP_AUTOMATIC_INTEGRATION_UNTIL_OWNERSHIP_RESOLVED" in proc.stdout
    assert "SYSTEM-LEVEL IMPLEMENTATION NOT STARTED" in proc.stdout


def test_the_conventional_matrix_path_is_connectivitys_own_filename(tmp_path):
    """One definition of where a connectivity matrix lives, so this module and
    emit_connectivity_artifacts() cannot disagree about the filename."""
    env = tmp_path / "env"
    (env / ".dv-harness").mkdir(parents=True)
    assert sri._conventional_matrix_path(str(env)) == ""
    target = env / ".dv-harness" / conn.ARTIFACT_FILENAMES["matrix_manifest"]
    _write_matrix(target, [])
    assert sri._conventional_matrix_path(str(env)) == str(target)
