"""Tests for dv_harness/command_task_trace.py -- DE-command-name traceability
by real grep-based cross-reference over a generated environment's files.

Fixture (`_write_fixture_env`) is a small, synthetic-but-realistic generated
environment shaped after this repo's own REAL generated evidence
(`examples/generated_usb_real_evidence_v1/`): a case-dispatch pattern pool
(`dv_uvm_pattern_pool.svh`'s real shape), a handler task carrying a real
`` `CPUWRITE1B `` macro invocation and a `// VIP:` citation comment (the real
convention `USB2_con_vip.txt` uses), a `` `define ``-redirect bridge file
(`dv_uvm_hook.svh`'s real shape: `` `CPUWRITE1B `` -> `dv_uvm_cpuwrite1b`), and
a scoreboard file citing a `` `FINAL_CHECK `` macro. Nothing here is mined
from a real project's content -- it is hand-authored to exercise this
module's own four legs, matching the SHAPE of real evidence already cited in
CLAUDE.md's Bind-Location Rules / pattern-architecture skill sections.
"""
from __future__ import annotations

import json
import shutil
import subprocess
import sys
import textwrap
from pathlib import Path

import pytest

from dv_harness import command_task_trace as ctt

ROOT = Path(__file__).resolve().parents[1]
requires_verible = pytest.mark.skipif(
    shutil.which("verible-verilog-syntax") is None,
    reason="verible-verilog-syntax not on PATH",
)


def _write_fixture_env(tmp_path: Path) -> Path:
    env_dir = tmp_path / "generated_env"
    (env_dir / "patterns_registry").mkdir(parents=True)
    (env_dir / "patterns").mkdir(parents=True)
    (env_dir / "bind").mkdir(parents=True)
    (env_dir / "env").mkdir(parents=True)

    (env_dir / "patterns_registry" / "dv_uvm_pattern_pool.svh").write_text(textwrap.dedent("""\
        // GENERATED by dv_harness/uvm_generator/pattern_registry_generator.py
        task automatic run_selected_pattern(string pattern_name);
          case (pattern_name)
            "USB2_con_vip": run_usb2_con_vip();
            default: `uvm_fatal("PATTERN_POOL", $sformatf("Unknown pattern '%s'", pattern_name))
          endcase
        endtask
        """), encoding="utf-8")

    (env_dir / "patterns" / "usb2_con_vip_task.sv").write_text(textwrap.dedent("""\
        task automatic run_usb2_con_vip();
          `CPUWRITE1B(32'h1270_0200, 8'h10); //usb ctrl rst=1
          svt_usb_agent_config vip_cfg;
          // VIP: svt_usb_agent configure HOST role
          $display("=>Dev Ctrl init done");
        endtask
        """), encoding="utf-8")

    (env_dir / "bind" / "dv_uvm_hook.svh").write_text(textwrap.dedent("""\
        // -- macro redirect (must precede the model's task definitions) --
        `define CPUWRITE1B dv_uvm_cpuwrite1b

        task automatic dv_uvm_cpuwrite1b(input [31:0] addr, input [7:0] data);
          uvm_config_db#(int)::set(null, "*", "cpuwrite1b_addr", addr);
        endtask
        """), encoding="utf-8")

    (env_dir / "env" / "usb_scoreboard.sv").write_text(textwrap.dedent("""\
        class usb_scoreboard extends uvm_scoreboard;
          `uvm_component_utils(usb_scoreboard)
          function void check_phase(uvm_phase phase);
            `FINAL_CHECK("USB2_con_vip")
          endfunction
        endclass
        """), encoding="utf-8")

    return env_dir


# --- positive path ------------------------------------------------------------

def test_full_chain_resolves_trace_complete_via_case_dispatch(tmp_path):
    env_dir = _write_fixture_env(tmp_path)
    report = ctt.trace_command("USB2_con_vip", env_dir, use_verible=False)
    assert report.status == ctt.STATUS_TRACE_COMPLETE
    assert report.reason is None

    task_leg = report.legs[ctt.LEG_TASK_MACRO]
    assert task_leg.status == ctt.LEG_RESOLVED
    kinds = {c.kind for c in task_leg.citations}
    assert "case_dispatch" in kinds
    assert "handler_task_declaration" in kinds

    bridge_leg = report.legs[ctt.LEG_UVM_BRIDGE]
    assert bridge_leg.status == ctt.LEG_RESOLVED
    assert any(c.kind == "macro_redirect_bridge" for c in bridge_leg.citations)

    vip_leg = report.legs[ctt.LEG_VIP_API]
    assert vip_leg.status == ctt.LEG_RESOLVED
    assert any(c.kind == "vip_comment_citation" for c in vip_leg.citations)

    checker_leg = report.legs[ctt.LEG_CHECKER]
    assert checker_leg.status == ctt.LEG_RESOLVED
    assert any(c.kind == "checker_macro_call" for c in checker_leg.citations)


def test_vip_prefix_widens_the_vip_leg(tmp_path):
    env_dir = _write_fixture_env(tmp_path)
    report = ctt.trace_command("USB2_con_vip", env_dir, vip_prefixes=["svt_"], use_verible=False)
    vip_leg = report.legs[ctt.LEG_VIP_API]
    assert vip_leg.status == ctt.LEG_RESOLVED
    kinds = {c.kind for c in vip_leg.citations}
    assert "vip_prefix_reference" in kinds
    assert any(c.detail == "svt_usb_agent_config" for c in vip_leg.citations)


def test_tracing_by_direct_task_name_also_resolves(tmp_path):
    env_dir = _write_fixture_env(tmp_path)
    report = ctt.trace_command("run_usb2_con_vip", env_dir, use_verible=False)
    task_leg = report.legs[ctt.LEG_TASK_MACRO]
    assert task_leg.status == ctt.LEG_RESOLVED
    assert any(c.kind == "task_declaration" for c in task_leg.citations)
    assert report.legs[ctt.LEG_UVM_BRIDGE].status == ctt.LEG_RESOLVED
    assert report.legs[ctt.LEG_VIP_API].status == ctt.LEG_RESOLVED


# --- negative controls ---------------------------------------------------------

def test_checker_leg_is_honestly_not_found_when_the_checker_cites_a_different_name(tmp_path):
    """The real scoreboard cites the PATTERN name ("USB2_con_vip"), not the raw
    handler task name -- tracing by the handler name alone must not fabricate a
    checker link that isn't textually there."""
    env_dir = _write_fixture_env(tmp_path)
    report = ctt.trace_command("run_usb2_con_vip", env_dir, use_verible=False)
    checker_leg = report.legs[ctt.LEG_CHECKER]
    assert checker_leg.status == ctt.LEG_NOT_FOUND
    assert checker_leg.citations == []
    assert report.status == ctt.STATUS_TRACE_PARTIAL
    assert ctt.LEG_CHECKER in report.reason


def test_missing_bridge_definition_yields_trace_partial(tmp_path):
    env_dir = _write_fixture_env(tmp_path)
    (env_dir / "bind" / "dv_uvm_hook.svh").unlink()
    report = ctt.trace_command("USB2_con_vip", env_dir, use_verible=False)
    assert report.legs[ctt.LEG_UVM_BRIDGE].status == ctt.LEG_NOT_FOUND
    assert report.status == ctt.STATUS_TRACE_PARTIAL
    assert ctt.LEG_UVM_BRIDGE in report.reason


def test_command_not_present_anywhere_is_not_found(tmp_path):
    env_dir = _write_fixture_env(tmp_path)
    report = ctt.trace_command("NO_SUCH_COMMAND_XYZ", env_dir, use_verible=False)
    assert report.status == ctt.STATUS_NOT_FOUND
    assert report.legs[ctt.LEG_TASK_MACRO].status == ctt.LEG_NOT_FOUND
    assert report.legs[ctt.LEG_TASK_MACRO].citations == []


def test_missing_env_dir_is_blocked(tmp_path):
    report = ctt.trace_command("USB2_con_vip", tmp_path / "does_not_exist", use_verible=False)
    assert report.status == ctt.STATUS_BLOCKED
    assert "does not exist" in report.reason


def test_empty_command_name_is_blocked(tmp_path):
    env_dir = _write_fixture_env(tmp_path)
    report = ctt.trace_command("   ", env_dir, use_verible=False)
    assert report.status == ctt.STATUS_BLOCKED
    assert "empty" in report.reason


def test_env_dir_with_no_source_files_is_blocked(tmp_path):
    env_dir = tmp_path / "empty_env"
    env_dir.mkdir()
    (env_dir / "README.md").write_text("nothing here", encoding="utf-8")
    report = ctt.trace_command("USB2_con_vip", env_dir, use_verible=False)
    assert report.status == ctt.STATUS_BLOCKED
    assert "no readable source files" in report.reason


def test_ambiguous_conflicting_task_declarations_never_reads_trace_complete(tmp_path):
    """Two genuinely different `task run_usb2_con_vip` declarations in two
    different files is a real textual ambiguity a declaration-level scan
    cannot resolve -- this must downgrade to TRACE_PARTIAL, never be silently
    picked one way or upgraded to TRACE_COMPLETE."""
    env_dir = _write_fixture_env(tmp_path)
    (env_dir / "patterns" / "usb2_con_vip_task_v2.sv").write_text(textwrap.dedent("""\
        task automatic run_usb2_con_vip();
          $display("a second, conflicting declaration of the same task name");
        endtask
        """), encoding="utf-8")
    report = ctt.trace_command("run_usb2_con_vip", env_dir, use_verible=False)
    task_leg = report.legs[ctt.LEG_TASK_MACRO]
    assert task_leg.status == ctt.LEG_AMBIGUOUS
    assert report.status == ctt.STATUS_TRACE_PARTIAL
    assert report.status != ctt.STATUS_TRACE_COMPLETE
    assert "distinct 'task run_usb2_con_vip'" in task_leg.reason


def test_ambiguous_case_dispatch_to_two_different_handlers(tmp_path):
    env_dir = _write_fixture_env(tmp_path)
    (env_dir / "patterns_registry" / "dv_uvm_pattern_pool_v2.svh").write_text(textwrap.dedent("""\
        task automatic run_selected_pattern_v2(string pattern_name);
          case (pattern_name)
            "USB2_con_vip": run_usb2_con_vip_alternate();
          endcase
        endtask
        """), encoding="utf-8")
    report = ctt.trace_command("USB2_con_vip", env_dir, use_verible=False)
    task_leg = report.legs[ctt.LEG_TASK_MACRO]
    assert task_leg.status == ctt.LEG_AMBIGUOUS
    assert report.status == ctt.STATUS_TRACE_PARTIAL


# --- verible enrichment (optional; skipped without the real binary) -----------

@requires_verible
def test_verible_confirms_the_real_task_signature(tmp_path):
    env_dir = _write_fixture_env(tmp_path)
    report = ctt.trace_command("run_usb2_con_vip", env_dir, use_verible=True)
    assert report.verible_status == "CONFIRMED"
    assert report.verible_signature is not None
    assert report.verible_signature["name"] == "run_usb2_con_vip"
    assert report.verible_signature["args"] == []


def test_verible_unavailable_binary_is_a_graceful_not_available_not_a_failure(tmp_path):
    env_dir = _write_fixture_env(tmp_path)
    report = ctt.trace_command("run_usb2_con_vip", env_dir, use_verible=True,
                                verible_bin="definitely-not-a-real-verible-binary-xyz")
    assert report.verible_status == "NOT_AVAILABLE"
    # the grep-based trace itself is unaffected by verible's absence -- the
    # same three legs that resolved with the real binary still resolve here
    assert report.legs[ctt.LEG_TASK_MACRO].status == ctt.LEG_RESOLVED
    assert report.legs[ctt.LEG_UVM_BRIDGE].status == ctt.LEG_RESOLVED
    assert report.legs[ctt.LEG_VIP_API].status == ctt.LEG_RESOLVED


def test_use_verible_false_is_recorded_as_skipped(tmp_path):
    env_dir = _write_fixture_env(tmp_path)
    report = ctt.trace_command("run_usb2_con_vip", env_dir, use_verible=False)
    assert report.verible_status == "SKIPPED"
    assert report.verible_signature is None


def test_verible_not_attempted_when_task_leg_resolves_only_via_dispatch(tmp_path):
    """The command "USB2_con_vip" resolves via case-dispatch, not a direct
    `task USB2_con_vip` declaration -- there is nothing named exactly that to
    hand verible, so enrichment must say NOT_ATTEMPTED rather than guess."""
    env_dir = _write_fixture_env(tmp_path)
    report = ctt.trace_command("USB2_con_vip", env_dir, use_verible=True)
    assert report.verible_status == "NOT_ATTEMPTED"
    assert report.verible_signature is None


# --- multi-command / exit-code plumbing ---------------------------------------

def test_trace_commands_and_overall_exit_code(tmp_path):
    env_dir = _write_fixture_env(tmp_path)
    reports = ctt.trace_commands(["USB2_con_vip", "NO_SUCH_COMMAND"], env_dir, use_verible=False)
    assert len(reports) == 2
    assert reports[0].status == ctt.STATUS_TRACE_COMPLETE
    assert reports[1].status == ctt.STATUS_NOT_FOUND
    assert ctt.overall_exit_code(reports) == 1

    blocked_reports = [ctt.trace_command("x", tmp_path / "nope", use_verible=False)]
    assert ctt.overall_exit_code(blocked_reports) == 2

    complete_reports = [ctt.trace_command("USB2_con_vip", env_dir, use_verible=False)]
    assert ctt.overall_exit_code(complete_reports) == 0


def test_trace_commands_refuses_an_empty_command_list(tmp_path):
    env_dir = _write_fixture_env(tmp_path)
    with pytest.raises(ctt.CommandTaskTraceError):
        ctt.trace_commands([], env_dir)


def test_format_report_mentions_status_and_citations(tmp_path):
    env_dir = _write_fixture_env(tmp_path)
    report = ctt.trace_command("USB2_con_vip", env_dir, use_verible=False)
    text = ctt.format_report(report)
    assert "TRACE_COMPLETE" in text
    assert ctt.LEG_TASK_MACRO in text
    assert "checker_macro_call" in text


# --- real generated environment already in this repo --------------------------

def test_against_a_real_generated_environment_reports_honestly(tmp_path):
    """Against this project's own real `examples/generated_usb_real_evidence_v1/`
    (produced by this project's own generator, not by this module), tracing a
    command name that really exists there via the real registry mapping must
    not crash and must produce a real, honestly-partial-or-better report --
    never a fabricated TRACE_COMPLETE for legs this real environment does not
    carry (its dv_uvm_hook.svh bridge instance is a real TODO_PLACEHOLDER, not
    a wired bridge)."""
    real_env = ROOT / "examples" / "generated_usb_real_evidence_v1"
    if not real_env.is_dir():
        pytest.skip("real fixture environment not present in this checkout")
    report = ctt.trace_command("USB2_con_vip", real_env, use_verible=False)
    assert report.status in (ctt.STATUS_TRACE_COMPLETE, ctt.STATUS_TRACE_PARTIAL,
                              ctt.STATUS_NOT_FOUND)
    assert report.files_scanned > 0
    task_leg = report.legs.get(ctt.LEG_TASK_MACRO)
    if task_leg is not None:
        assert task_leg.status in (ctt.LEG_RESOLVED, ctt.LEG_AMBIGUOUS)


# --- CLI, driven as a real subprocess -------------------------------------------

def test_cli_json_and_exit_code(tmp_path):
    env_dir = _write_fixture_env(tmp_path)
    proc = subprocess.run(
        [sys.executable, "-m", "dv_harness.command_task_trace",
         "--env-dir", str(env_dir), "--command", "USB2_con_vip",
         "--no-verible", "--json"],
        cwd=str(ROOT), capture_output=True, text=True, timeout=60)
    assert proc.returncode == 0, proc.stderr
    payload = json.loads(proc.stdout)
    assert payload[0]["status"] == ctt.STATUS_TRACE_COMPLETE


def test_cli_exit_code_1_on_not_found(tmp_path):
    env_dir = _write_fixture_env(tmp_path)
    proc = subprocess.run(
        [sys.executable, "-m", "dv_harness.command_task_trace",
         "--env-dir", str(env_dir), "--command", "NO_SUCH_COMMAND", "--no-verible"],
        cwd=str(ROOT), capture_output=True, text=True, timeout=60)
    assert proc.returncode == 1, proc.stderr


def test_cli_exit_code_2_on_blocked(tmp_path):
    proc = subprocess.run(
        [sys.executable, "-m", "dv_harness.command_task_trace",
         "--env-dir", str(tmp_path / "nope"), "--command", "X", "--no-verible"],
        cwd=str(ROOT), capture_output=True, text=True, timeout=60)
    assert proc.returncode == 2, proc.stderr
