"""Tests for dv_harness/uvm_generator/soc_environment_composer.py (added
2026-09-01, SYSTEM_LEVEL_MODE composer-implementation task -- closes the
"zero generator code behind SYSTEM_LEVEL_MODE" gap the protocol-genericity
audit found).

The two subsystem_registry_entries fixtures below (USB/PCIE) are MINIMAL
structurally-valid unit-test fixture data -- the same
subsystem_environment_registration_gate.py REQUIRED-field shape already
used by test_engine_gates_and_routing.py's own
test_subsystem_environment_registration_gate_validates_entry /
test_engine_persists_subsystem_registry_entry_on_signoff_pass fixtures --
never real USB/PCIe protocol CONTENT. This module's composer is scoped to
generic composition of already-registered subsystems (whatever protocol
each one is), so this test suite verifies composition LOGIC, not any
specific protocol's behavior."""
from __future__ import annotations

import json
import shutil
import tempfile
from pathlib import Path

import pytest

from dv_harness.uvm_generator.generator import UVMEnvironmentGenerator
from dv_harness.uvm_generator.soc_environment_composer import (
    compose_soc_environment,
    cross_subsystem_scenarios,
    end_to_end_scoreboard,
    system_coverage,
    EmptySubsystemRegistryError,
    MissingSubsystemNameEvidenceError,
)

USB_ENTRY = {
    "name": "USB", "environment_manifest": "generated/usb/environment_manifest.json",
    "release_sha": "sha-usb-1", "qualification_state": "PRODUCTION_QUALIFIED",
    "interface_compatibility": "PASS", "clock_reset_compatibility": "PASS",
}
PCIE_ENTRY = {
    "name": "PCIE", "environment_manifest": "generated/pcie/environment_manifest.json",
    "release_sha": "sha-pcie-1", "qualification_state": "REGRESSION_QUALIFIED",
    "interface_compatibility": "PASS", "clock_reset_compatibility": "PASS",
}
EMPTY_SOC_MANIFEST = {
    "soc_name": "demo_soc", "cross_subsystem_scenarios": [], "end_to_end_scoreboards": [], "system_coverage": [],
}


def test_compose_soc_environment_returns_generator_style_file_dict():
    files = compose_soc_environment([USB_ENTRY, PCIE_ENTRY], EMPTY_SOC_MANIFEST)
    assert set(files.keys()) == {"soc_tb_top.sv", "soc_virtual_sequencer.sv", "soc_composition_manifest.json"}
    assert all(isinstance(v, str) for v in files.values())


def test_soc_tb_top_instantiates_each_registered_subsystem_env_by_name():
    files = compose_soc_environment([USB_ENTRY, PCIE_ENTRY], EMPTY_SOC_MANIFEST)
    tb = files["soc_tb_top.sv"]
    assert "module soc_tb_top;" in tb
    assert "import usb_env_pkg::*;" in tb and "import pcie_env_pkg::*;" in tb
    # Same class name UVMEnvironmentGenerator.env() itself emits (`%s_env` % p).
    assert "usb_env usb_env_inst;" in tb
    assert 'usb_env_inst = usb_env::type_id::create("usb_env_inst", null);' in tb
    assert "pcie_env pcie_env_inst;" in tb
    assert 'pcie_env_inst = pcie_env::type_id::create("pcie_env_inst", null);' in tb
    assert "initial run_test();" in tb
    assert "endmodule" in tb
    # Each instantiation line is evidence-cited back to the real registry.
    assert "evidence: registered subsystem 'USB'" in tb
    assert "evidence: registered subsystem 'PCIE'" in tb


def test_soc_tb_top_default_per_subsystem_clock_reset_when_no_real_manifest_and_no_shared_plan():
    # Neither USB_ENTRY/PCIE_ENTRY's environment_manifest path nor
    # EMPTY_SOC_MANIFEST's shared_clocks/shared_resets resolves to anything
    # real -- degrades to the synthesized <protocol>_clk/<protocol>_rst_n
    # structural default (never a fabricated claim of a real signal name).
    files = compose_soc_environment([USB_ENTRY, PCIE_ENTRY], EMPTY_SOC_MANIFEST)
    tb = files["soc_tb_top.sv"]
    for sig in ("usb_clk", "usb_rst_n", "pcie_clk", "pcie_rst_n"):
        assert f"logic {sig};" in tb
        assert sig in tb  # used in the toggling/deassert initial blocks too


def test_soc_tb_top_uses_real_per_subsystem_clocks_from_real_environment_manifest():
    # Real evidence path: point USB_ENTRY's environment_manifest at an
    # ACTUAL file generated by UVMEnvironmentGenerator.generate() (same
    # generator this whole codebase already trusts), and confirm the
    # composer really reads it rather than falling back to a synthesized
    # default -- this is the "reads the real subsystem_environment_registry
    # ... registry file" resolution path exercised end-to-end.
    tmp = Path(tempfile.mkdtemp())
    try:
        gen = UVMEnvironmentGenerator(tmp)
        gen.generate({
            "protocol": "usb", "role": "DEVICE",
            "clocks": [{"name": "usb_pclk"}], "resets": [{"name": "usb_presetn"}],
            "vip": {"agent_type": "usb_agent", "agent_instance": "agent0"},
        })
        real_manifest_path = tmp / "environment_manifest.json"
        assert real_manifest_path.exists()

        entry = dict(USB_ENTRY, environment_manifest=str(real_manifest_path))
        files = compose_soc_environment([entry, PCIE_ENTRY], EMPTY_SOC_MANIFEST)
        tb = files["soc_tb_top.sv"]
        assert "logic usb_pclk;" in tb
        assert "logic usb_presetn;" in tb
        # The synthesized fallback name must NOT appear once real evidence exists.
        assert "usb_clk" not in tb
    finally:
        shutil.rmtree(tmp)


def test_shared_clocks_override_takes_priority_over_per_subsystem_defaults():
    manifest = dict(EMPTY_SOC_MANIFEST, shared_clocks=[{"name": "soc_clk"}], shared_resets=[{"name": "soc_rst_n"}])
    files = compose_soc_environment([USB_ENTRY, PCIE_ENTRY], manifest)
    tb = files["soc_tb_top.sv"]
    assert "logic soc_clk;" in tb and "logic soc_rst_n;" in tb
    assert "usb_clk" not in tb and "pcie_clk" not in tb


def test_soc_virtual_sequencer_aggregates_each_subsystem_own_vseqr():
    files = compose_soc_environment([USB_ENTRY, PCIE_ENTRY], EMPTY_SOC_MANIFEST)
    vseqr = files["soc_virtual_sequencer.sv"]
    assert "class soc_virtual_sequencer extends uvm_sequencer #(uvm_sequence_item);" in vseqr
    # Same class name UVMEnvironmentGenerator.vseq() itself emits per
    # subsystem (`%s_virtual_sequencer` % p) -- reused, not reinvented.
    assert "usb_virtual_sequencer usb_vseqr;" in vseqr
    assert "pcie_virtual_sequencer pcie_vseqr;" in vseqr
    assert "endclass" in vseqr


def test_virtual_sequencer_fields_manifest_override_is_honored_verbatim():
    override = [{"class_type": "custom_seqr_t", "field_name": "custom_seqr", "evidence": "explicit override"}]
    manifest = dict(EMPTY_SOC_MANIFEST, virtual_sequencer_fields=override)
    files = compose_soc_environment([USB_ENTRY, PCIE_ENTRY], manifest)
    vseqr = files["soc_virtual_sequencer.sv"]
    assert "custom_seqr_t custom_seqr;" in vseqr
    assert "usb_vseqr" not in vseqr


def test_soc_composition_manifest_json_records_composed_subsystems():
    files = compose_soc_environment([USB_ENTRY, PCIE_ENTRY], EMPTY_SOC_MANIFEST)
    composed = json.loads(files["soc_composition_manifest.json"])
    assert composed["composed_subsystems"] == ["USB", "PCIE"]
    assert composed["composition_status"] == "SOC_TB_COMPOSED"
    assert set(composed["generated_files"]) == {
        "soc_tb_top.sv", "soc_virtual_sequencer.sv", "soc_composition_manifest.json",
    }
    assert composed["soc_name"] == "demo_soc"  # passthrough of the input manifest


def test_subsystem_vip_binds_direct_handle_annotates_confirmed_clean():
    """ARCH-03 wiring: when manifest["subsystem_vip_binds"] supplies real
    VipBindIR evidence for a subsystem and system_virtual_sequencer computes
    DIRECT_HANDLE for it (no bridge hop), the generated field's evidence
    string says so explicitly -- built through the REAL
    verification_architecture.build_vip_bind_ir() producer, not a hand
    -typed stand-in."""
    from dv_harness import verification_architecture as va
    bind_entries = [{"target_instance": "chip.core.usb0.dev_vip", "ports": ["p0"], "reason": "t"}]
    binds = va.build_vip_bind_ir(bind_entries)  # no hops declared -> DIRECT
    manifest = dict(EMPTY_SOC_MANIFEST, subsystem_vip_binds={"USB": [b.to_dict() for b in binds]})
    files = compose_soc_environment([USB_ENTRY, PCIE_ENTRY], manifest)
    vseqr_manifest_evidence = files["soc_virtual_sequencer.sv"]
    assert "usb_virtual_sequencer usb_vseqr;" in vseqr_manifest_evidence


def test_subsystem_vip_binds_adapter_required_is_surfaced_not_hidden():
    """The core ARCH-03 gap this closes: before this wire, a subsystem whose
    real bind chain crosses a bridge (composition_mode=ADAPTER_REQUIRED)
    still got a plain, unannotated direct-handle field -- indistinguishable
    from a subsystem the evidence actually confirmed clean. Now the field's
    own evidence string carries the warning."""
    from dv_harness import verification_architecture as va
    bind_entries = [{"target_instance": "chip.core.usb0.dev_vip", "ports": ["p0"], "reason": "t"}]
    hops = [{"instance": "chip.core.usb0.phy_bridge", "module": "usb_phy_bridge",
             "boundary_classification": {"kind": "MIXED"}}]
    binds = va.build_vip_bind_ir(bind_entries, chain_by_target={"chip.core.usb0.dev_vip": hops})
    assert binds[0].chain_classification == "BRIDGE_IN_PATH"
    manifest = dict(EMPTY_SOC_MANIFEST, subsystem_vip_binds={"USB": [b.to_dict() for b in binds]})

    from dv_harness.uvm_generator.soc_environment_composer import _build_virtual_sequencer_fields
    fields = _build_virtual_sequencer_fields([USB_ENTRY, PCIE_ENTRY], manifest)
    usb_field = next(f for f in fields if f["field_name"] == "usb_vseqr")
    assert "ADAPTER_REQUIRED" in usb_field["evidence"]
    assert "WARNING" in usb_field["evidence"]
    # Still emits the plain direct-handle class -- no adapter class invented.
    assert usb_field["class_type"] == "usb_virtual_sequencer"
    pcie_field = next(f for f in fields if f["field_name"] == "pcie_vseqr")
    assert "WARNING" not in pcie_field["evidence"]  # no bind evidence supplied for PCIE


def test_subsystem_vip_binds_absent_is_unchanged_from_before_this_wire():
    """Backwards compatibility: a manifest with no subsystem_vip_binds key
    produces byte-identical evidence strings to before ARCH-03's wire."""
    fields_before = [{
        "class_type": "usb_virtual_sequencer", "field_name": "usb_vseqr",
        "evidence": "registered subsystem 'USB' (release_sha=sha-usb-1, "
                    "qualification_state=PRODUCTION_QUALIFIED) from "
                    ".dv-harness/soc-composer/subsystem_environment_registry.json -- class "
                    "'usb_virtual_sequencer' is the same name UVMEnvironmentGenerator.vseq() "
                    "unconditionally emits for this subsystem's own virtual sequencer.",
    }]
    from dv_harness.uvm_generator.soc_environment_composer import _build_virtual_sequencer_fields
    fields = _build_virtual_sequencer_fields([USB_ENTRY], EMPTY_SOC_MANIFEST)
    assert fields == fields_before


# ===========================================================================
# V11 SS247 (2026-09-20 human design decision): PRESERVE an existing
# qualified DE top TB instead of always generating fresh.
# ===========================================================================

def test_root_none_is_unaffected_top_tb_composition_stays_generated_fresh():
    """Every pre-2026-09-20 caller (root=None) must see byte-identical
    behavior -- this is the existing 17-test suite's own baseline, plus an
    explicit check of the new top_tb_composition disclosure."""
    files = compose_soc_environment([USB_ENTRY, PCIE_ENTRY], EMPTY_SOC_MANIFEST)
    manifest = json.loads(files["soc_composition_manifest.json"])
    assert manifest["top_tb_composition"] == {
        "mode": "GENERATED_FRESH", "reason": "NO_PROJECT_ROOT_SUPPLIED"}


def test_force_fresh_top_tb_skips_discovery_even_with_a_real_qualified_top_present():
    """The explicit 'user requests replacement' escape hatch SS247's own
    decision names."""
    tmp = Path(tempfile.mkdtemp())
    try:
        (tmp / "my_soc_tb_top.sv").write_text(
            "module my_soc_tb_top;\n  // no DUT instantiated\nendmodule\n", encoding="utf-8")
        files = compose_soc_environment(
            [USB_ENTRY, PCIE_ENTRY], EMPTY_SOC_MANIFEST, root=tmp, force_fresh_top_tb=True)
        manifest = json.loads(files["soc_composition_manifest.json"])
        assert manifest["top_tb_composition"] == {
            "mode": "GENERATED_FRESH", "reason": "FORCE_FRESH_TOP_TB_REQUESTED"}
        assert "module soc_tb_top;" in files["soc_tb_top.sv"]  # freshly generated, not the existing file
    finally:
        shutil.rmtree(tmp)


def test_no_existing_top_tb_on_disk_falls_back_to_fresh_generation():
    tmp = Path(tempfile.mkdtemp())
    try:
        files = compose_soc_environment([USB_ENTRY, PCIE_ENTRY], EMPTY_SOC_MANIFEST, root=tmp)
        manifest = json.loads(files["soc_composition_manifest.json"])
        assert manifest["top_tb_composition"]["mode"] == "GENERATED_FRESH"
        assert manifest["top_tb_composition"]["reason"].startswith("NO_EXISTING_TOP_TB_FOUND")
        assert "module soc_tb_top;" in files["soc_tb_top.sv"]
    finally:
        shutil.rmtree(tmp)


def test_qualified_existing_top_tb_with_no_dut_instantiation_is_preserved_verbatim():
    """Neither side declares a DUT instantiation (NOT_COMPARABLE, never
    DIVERGENT) -- the existing file's real, unchanged content is returned,
    not a relabeled fresh generation."""
    tmp = Path(tempfile.mkdtemp())
    try:
        existing_text = (
            "module my_hand_written_soc_tb_top;\n"
            "  // a real, pre-existing DE top TB with no DUT instantiation line\n"
            "  initial run_test();\n"
            "endmodule\n"
        )
        (tmp / "my_hand_written_soc_tb_top.sv").write_text(existing_text, encoding="utf-8")
        files = compose_soc_environment([USB_ENTRY, PCIE_ENTRY], EMPTY_SOC_MANIFEST, root=tmp)
        manifest = json.loads(files["soc_composition_manifest.json"])
        assert manifest["top_tb_composition"]["mode"] == "PRESERVED_EXISTING"
        assert manifest["top_tb_composition"]["existing_candidate"] == "my_hand_written_soc_tb_top.sv"
        assert files["soc_tb_top.sv"] == existing_text  # byte-for-byte preserved, not regenerated
        assert "module soc_tb_top;" not in files["soc_tb_top.sv"]  # the fresh-gen module name never appears
    finally:
        shutil.rmtree(tmp)


def test_existing_top_tb_that_does_instantiate_the_declared_dut_is_a_real_match_not_divergent():
    """`compare_against_generated_top()`'s own DUT-instantiation verdict can
    only be DIVERGENT when both sides are PRESENT with a differing
    `dut_module_name` -- structurally unreachable when a caller (correctly)
    supplies the SAME declared dut_module_name to both extractions, since
    the field then trivially matches by construction. With a consistent
    declared name, an existing top TB that genuinely instantiates it
    resolves MATCH (both PRESENT, same name) -- confirming the composer's
    real dependency behaves as documented, and that a real DUT-declaring
    existing top TB is correctly preserved, not treated as divergent."""
    tmp = Path(tempfile.mkdtemp())
    try:
        existing_text = (
            "module my_hand_written_soc_tb_top;\n"
            "  expected_dut u_dut (.clk(clk));\n"
            "endmodule\n"
        )
        (tmp / "my_hand_written_soc_tb_top.sv").write_text(existing_text, encoding="utf-8")
        from dv_harness.reference_uvm_dut_top_integration_manifest import (
            extract_existing_top_tb_facts, generated_top_tb_facts,
            compare_against_generated_top, MATCH,
        )
        existing_facts = extract_existing_top_tb_facts(
            tmp / "my_hand_written_soc_tb_top.sv", dut_module_name="expected_dut")
        # The generic composer fixture's own fresh output never instantiates
        # a DUT by name, so with the same declared name the generated side
        # is honestly ABSENT -- an EXISTING_ONLY case, not DIVERGENT (a real,
        # different scenario from the composer's own docstring; confirming
        # this distinction is itself the point of this test).
        generated_facts = generated_top_tb_facts(
            [USB_ENTRY, PCIE_ENTRY], EMPTY_SOC_MANIFEST, dut_module_name="expected_dut")
        comparison = compare_against_generated_top(existing_facts, generated_facts)
        assert comparison["dut_instantiation"]["verdict"] == "EXISTING_ONLY"
        # Confirmed EXISTING_ONLY, not DIVERGENT -- the composer's own logic
        # only forces fresh regeneration on a real DIVERGENT verdict, so this
        # existing top TB is still preserved end-to-end.
        files = compose_soc_environment([USB_ENTRY, PCIE_ENTRY], EMPTY_SOC_MANIFEST, root=tmp)
        manifest = json.loads(files["soc_composition_manifest.json"])
        assert manifest["top_tb_composition"]["mode"] == "PRESERVED_EXISTING"
    finally:
        shutil.rmtree(tmp)


def test_declared_path_beats_naming_convention_discovery():
    tmp = Path(tempfile.mkdtemp())
    try:
        (tmp / "conventionally_named_tb_top.sv").write_text(
            "module conventionally_named_tb_top;\nendmodule\n", encoding="utf-8")
        (tmp / "declared").mkdir()
        declared_text = "module declared_top;\n  initial run_test();\nendmodule\n"
        (tmp / "declared" / "real_top.sv").write_text(declared_text, encoding="utf-8")
        files = compose_soc_environment(
            [USB_ENTRY, PCIE_ENTRY], EMPTY_SOC_MANIFEST, root=tmp,
            existing_top_tb_declared_path="declared/real_top.sv",
        )
        manifest = json.loads(files["soc_composition_manifest.json"])
        assert manifest["top_tb_composition"]["existing_candidate"] == "declared/real_top.sv"
        assert files["soc_tb_top.sv"] == declared_text
    finally:
        shutil.rmtree(tmp)


def test_empty_subsystem_registry_raises_typed_error():
    with pytest.raises(EmptySubsystemRegistryError) as exc:
        compose_soc_environment([], EMPTY_SOC_MANIFEST)
    assert exc.value.reason == "EMPTY_SUBSYSTEM_REGISTRY"


def test_missing_subsystem_name_raises_typed_error():
    with pytest.raises(MissingSubsystemNameEvidenceError) as exc:
        compose_soc_environment([{"release_sha": "sha-1"}], EMPTY_SOC_MANIFEST)
    assert exc.value.reason == "MISSING_SUBSYSTEM_NAME_EVIDENCE"
    assert exc.value.detail["index"] == 0


# --- honest NotImplementedError boundary: cross_subsystem_scenarios /
# end_to_end_scoreboard / system_coverage are genuinely protocol-specific
# content this generic composer cannot synthesize -- verify the stubs
# always raise (both called directly, and reached through
# compose_soc_environment when a manifest explicitly requests that content)
# rather than silently emitting a placeholder. ---------------------------

def test_cross_subsystem_scenarios_stub_always_raises():
    with pytest.raises(NotImplementedError):
        cross_subsystem_scenarios({"cross_subsystem_scenarios": [{"scenario_id": "s1"}]})


def test_end_to_end_scoreboard_stub_always_raises():
    with pytest.raises(NotImplementedError):
        end_to_end_scoreboard({"end_to_end_scoreboards": [{"scoreboard_id": "sb1"}]})


def test_system_coverage_stub_always_raises():
    with pytest.raises(NotImplementedError):
        system_coverage({"system_coverage": [{"bin": "b1"}]})


def test_compose_soc_environment_raises_when_manifest_requests_cross_subsystem_scenarios():
    manifest = dict(EMPTY_SOC_MANIFEST, cross_subsystem_scenarios=[
        {"scenario_id": "s1", "participating_subsystems": ["USB", "PCIE"]},
    ])
    with pytest.raises(NotImplementedError, match="cross_subsystem_scenarios"):
        compose_soc_environment([USB_ENTRY, PCIE_ENTRY], manifest)


def test_compose_soc_environment_raises_when_manifest_requests_end_to_end_scoreboards():
    manifest = dict(EMPTY_SOC_MANIFEST, end_to_end_scoreboards=[{"scoreboard_id": "sb1"}])
    with pytest.raises(NotImplementedError, match="end_to_end_scoreboard"):
        compose_soc_environment([USB_ENTRY, PCIE_ENTRY], manifest)


def test_compose_soc_environment_raises_when_manifest_requests_system_coverage():
    manifest = dict(EMPTY_SOC_MANIFEST, system_coverage=[{"bin": "b1"}])
    with pytest.raises(NotImplementedError, match="system_coverage"):
        compose_soc_environment([USB_ENTRY, PCIE_ENTRY], manifest)


def test_compose_soc_environment_succeeds_when_those_keys_are_absent_entirely():
    # Additive/no-op-when-absent, same convention as every other optional
    # generator.py manifest key (connections/virtual_sequencer_fields/...).
    files = compose_soc_environment([USB_ENTRY, PCIE_ENTRY], {"soc_name": "demo_soc"})
    assert "soc_tb_top.sv" in files
