"""Tests for dv_harness/uvm_generator/soc_environment_composer.py (added
2026-09-01, SYSTEM_LEVEL_MODE composer-implementation task -- closes the
"zero generator code behind SYSTEM_LEVEL_MODE" gap the protocol-genericity
audit found).

The two subsystem_registry_entries fixtures below (USB/PCIE) are MINIMAL
structurally-valid unit-test fixture data -- the same
subsystem_environment_registration_gate.py REQUIRED-field shape already
used by test_engine_gates_and_routing.py's own
test_subsystem_environment_registration_gate_validates_entry /
test_engine_persists_subsystem_registry_entry_on_signoff_pass fixtures --
never real USB/PCIe protocol CONTENT. This module's composer is scoped to
generic composition of already-registered subsystems (whatever protocol
each one is), so this test suite verifies composition LOGIC, not any
specific protocol's behavior."""
from __future__ import annotations

import json
import shutil
import tempfile
from pathlib import Path

import pytest

from dv_harness.uvm_generator.generator import UVMEnvironmentGenerator
from dv_harness.uvm_generator.soc_environment_composer import (
    compose_soc_environment,
    cross_subsystem_scenarios,
    end_to_end_scoreboard,
    system_coverage,
    EmptySubsystemRegistryError,
    MissingSubsystemNameEvidenceError,
)

USB_ENTRY = {
    "name": "USB", "environment_manifest": "generated/usb/environment_manifest.json",
    "release_sha": "sha-usb-1", "qualification_state": "PRODUCTION_QUALIFIED",
    "interface_compatibility": "PASS", "clock_reset_compatibility": "PASS",
}
PCIE_ENTRY = {
    "name": "PCIE", "environment_manifest": "generated/pcie/environment_manifest.json",
    "release_sha": "sha-pcie-1", "qualification_state": "REGRESSION_QUALIFIED",
    "interface_compatibility": "PASS", "clock_reset_compatibility": "PASS",
}
EMPTY_SOC_MANIFEST = {
    "soc_name": "demo_soc", "cross_subsystem_scenarios": [], "end_to_end_scoreboards": [], "system_coverage": [],
}


def test_compose_soc_environment_returns_generator_style_file_dict():
    files = compose_soc_environment([USB_ENTRY, PCIE_ENTRY], EMPTY_SOC_MANIFEST)
    assert set(files.keys()) == {"soc_tb_top.sv", "soc_virtual_sequencer.sv", "soc_composition_manifest.json"}
    assert all(isinstance(v, str) for v in files.values())


def test_soc_tb_top_instantiates_each_registered_subsystem_env_by_name():
    files = compose_soc_environment([USB_ENTRY, PCIE_ENTRY], EMPTY_SOC_MANIFEST)
    tb = files["soc_tb_top.sv"]
    assert "module soc_tb_top;" in tb
    assert "import usb_env_pkg::*;" in tb and "import pcie_env_pkg::*;" in tb
    # Same class name UVMEnvironmentGenerator.env() itself emits (`%s_env` % p).
    assert "usb_env usb_env_inst;" in tb
    assert 'usb_env_inst = usb_env::type_id::create("usb_env_inst", null);' in tb
    assert "pcie_env pcie_env_inst;" in tb
    assert 'pcie_env_inst = pcie_env::type_id::create("pcie_env_inst", null);' in tb
    assert "initial run_test();" in tb
    assert "endmodule" in tb
    # Each instantiation line is evidence-cited back to the real registry.
    assert "evidence: registered subsystem 'USB'" in tb
    assert "evidence: registered subsystem 'PCIE'" in tb


def test_soc_tb_top_default_per_subsystem_clock_reset_when_no_real_manifest_and_no_shared_plan():
    # Neither USB_ENTRY/PCIE_ENTRY's environment_manifest path nor
    # EMPTY_SOC_MANIFEST's shared_clocks/shared_resets resolves to anything
    # real -- degrades to the synthesized <protocol>_clk/<protocol>_rst_n
    # structural default (never a fabricated claim of a real signal name).
    files = compose_soc_environment([USB_ENTRY, PCIE_ENTRY], EMPTY_SOC_MANIFEST)
    tb = files["soc_tb_top.sv"]
    for sig in ("usb_clk", "usb_rst_n", "pcie_clk", "pcie_rst_n"):
        assert f"logic {sig};" in tb
        assert sig in tb  # used in the toggling/deassert initial blocks too


def test_soc_tb_top_uses_real_per_subsystem_clocks_from_real_environment_manifest():
    # Real evidence path: point USB_ENTRY's environment_manifest at an
    # ACTUAL file generated by UVMEnvironmentGenerator.generate() (same
    # generator this whole codebase already trusts), and confirm the
    # composer really reads it rather than falling back to a synthesized
    # default -- this is the "reads the real subsystem_environment_registry
    # ... registry file" resolution path exercised end-to-end.
    tmp = Path(tempfile.mkdtemp())
    try:
        gen = UVMEnvironmentGenerator(tmp)
        gen.generate({
            "protocol": "usb", "role": "DEVICE",
            "clocks": [{"name": "usb_pclk"}], "resets": [{"name": "usb_presetn"}],
            "vip": {"agent_type": "usb_agent", "agent_instance": "agent0"},
        })
        real_manifest_path = tmp / "environment_manifest.json"
        assert real_manifest_path.exists()

        entry = dict(USB_ENTRY, environment_manifest=str(real_manifest_path))
        files = compose_soc_environment([entry, PCIE_ENTRY], EMPTY_SOC_MANIFEST)
        tb = files["soc_tb_top.sv"]
        assert "logic usb_pclk;" in tb
        assert "logic usb_presetn;" in tb
        # The synthesized fallback name must NOT appear once real evidence exists.
        assert "usb_clk" not in tb
    finally:
        shutil.rmtree(tmp)


def test_shared_clocks_override_takes_priority_over_per_subsystem_defaults():
    manifest = dict(EMPTY_SOC_MANIFEST, shared_clocks=[{"name": "soc_clk"}], shared_resets=[{"name": "soc_rst_n"}])
    files = compose_soc_environment([USB_ENTRY, PCIE_ENTRY], manifest)
    tb = files["soc_tb_top.sv"]
    assert "logic soc_clk;" in tb and "logic soc_rst_n;" in tb
    assert "usb_clk" not in tb and "pcie_clk" not in tb


def test_soc_virtual_sequencer_aggregates_each_subsystem_own_vseqr():
    files = compose_soc_environment([USB_ENTRY, PCIE_ENTRY], EMPTY_SOC_MANIFEST)
    vseqr = files["soc_virtual_sequencer.sv"]
    assert "class soc_virtual_sequencer extends uvm_sequencer #(uvm_sequence_item);" in vseqr
    # Same class name UVMEnvironmentGenerator.vseq() itself emits per
    # subsystem (`%s_virtual_sequencer` % p) -- reused, not reinvented.
    assert "usb_virtual_sequencer usb_vseqr;" in vseqr
    assert "pcie_virtual_sequencer pcie_vseqr;" in vseqr
    assert "endclass" in vseqr


def test_virtual_sequencer_fields_manifest_override_is_honored_verbatim():
    override = [{"class_type": "custom_seqr_t", "field_name": "custom_seqr", "evidence": "explicit override"}]
    manifest = dict(EMPTY_SOC_MANIFEST, virtual_sequencer_fields=override)
    files = compose_soc_environment([USB_ENTRY, PCIE_ENTRY], manifest)
    vseqr = files["soc_virtual_sequencer.sv"]
    assert "custom_seqr_t custom_seqr;" in vseqr
    assert "usb_vseqr" not in vseqr


def test_soc_composition_manifest_json_records_composed_subsystems():
    files = compose_soc_environment([USB_ENTRY, PCIE_ENTRY], EMPTY_SOC_MANIFEST)
    composed = json.loads(files["soc_composition_manifest.json"])
    assert composed["composed_subsystems"] == ["USB", "PCIE"]
    assert composed["composition_status"] == "SOC_TB_COMPOSED"
    assert set(composed["generated_files"]) == {
        "soc_tb_top.sv", "soc_virtual_sequencer.sv", "soc_composition_manifest.json",
    }
    assert composed["soc_name"] == "demo_soc"  # passthrough of the input manifest


def test_empty_subsystem_registry_raises_typed_error():
    with pytest.raises(EmptySubsystemRegistryError) as exc:
        compose_soc_environment([], EMPTY_SOC_MANIFEST)
    assert exc.value.reason == "EMPTY_SUBSYSTEM_REGISTRY"


def test_missing_subsystem_name_raises_typed_error():
    with pytest.raises(MissingSubsystemNameEvidenceError) as exc:
        compose_soc_environment([{"release_sha": "sha-1"}], EMPTY_SOC_MANIFEST)
    assert exc.value.reason == "MISSING_SUBSYSTEM_NAME_EVIDENCE"
    assert exc.value.detail["index"] == 0


# --- honest NotImplementedError boundary: cross_subsystem_scenarios /
# end_to_end_scoreboard / system_coverage are genuinely protocol-specific
# content this generic composer cannot synthesize -- verify the stubs
# always raise (both called directly, and reached through
# compose_soc_environment when a manifest explicitly requests that content)
# rather than silently emitting a placeholder. ---------------------------

def test_cross_subsystem_scenarios_stub_always_raises():
    with pytest.raises(NotImplementedError):
        cross_subsystem_scenarios({"cross_subsystem_scenarios": [{"scenario_id": "s1"}]})


def test_end_to_end_scoreboard_stub_always_raises():
    with pytest.raises(NotImplementedError):
        end_to_end_scoreboard({"end_to_end_scoreboards": [{"scoreboard_id": "sb1"}]})


def test_system_coverage_stub_always_raises():
    with pytest.raises(NotImplementedError):
        system_coverage({"system_coverage": [{"bin": "b1"}]})


def test_compose_soc_environment_raises_when_manifest_requests_cross_subsystem_scenarios():
    manifest = dict(EMPTY_SOC_MANIFEST, cross_subsystem_scenarios=[
        {"scenario_id": "s1", "participating_subsystems": ["USB", "PCIE"]},
    ])
    with pytest.raises(NotImplementedError, match="cross_subsystem_scenarios"):
        compose_soc_environment([USB_ENTRY, PCIE_ENTRY], manifest)


def test_compose_soc_environment_raises_when_manifest_requests_end_to_end_scoreboards():
    manifest = dict(EMPTY_SOC_MANIFEST, end_to_end_scoreboards=[{"scoreboard_id": "sb1"}])
    with pytest.raises(NotImplementedError, match="end_to_end_scoreboard"):
        compose_soc_environment([USB_ENTRY, PCIE_ENTRY], manifest)


def test_compose_soc_environment_raises_when_manifest_requests_system_coverage():
    manifest = dict(EMPTY_SOC_MANIFEST, system_coverage=[{"bin": "b1"}])
    with pytest.raises(NotImplementedError, match="system_coverage"):
        compose_soc_environment([USB_ENTRY, PCIE_ENTRY], manifest)


def test_compose_soc_environment_succeeds_when_those_keys_are_absent_entirely():
    # Additive/no-op-when-absent, same convention as every other optional
    # generator.py manifest key (connections/virtual_sequencer_fields/...).
    files = compose_soc_environment([USB_ENTRY, PCIE_ENTRY], {"soc_name": "demo_soc"})
    assert "soc_tb_top.sv" in files
